### ISSUE TITLE
Content Provider Leakage Challenge Coverage

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#102]
Transferred from LATAM Repo: https://github.com/markdenihan/LatamOwaspSecurityShepherd/issues/11

**Comment by SeanDuggan** [comment]
-Finished App, current key needs to be initialized on startup.
-Level hash has to be generated
-Web App level page needs to be made

This is probably gonna be a challenge, lesson will be similar but easier.

**Comment by SeanDuggan** [comment]
Done.

Closing this, final result was a lesson where the user is told the URI and the commands to grab data from it.

Will make a challenge with a hidden uri and a player will need to enumerate them all.
