### ISSUE TITLE
Poor Authentication Challenge 2

### ISSUE THREAD

**Issue by SeanDuggan** [OWASP/SecurityShepherd#111]
An hidden activity which only authenticated users are allowed to access, unprotected from other apps opening the activity. The activity in question contains the key. A player will have to use adb am or drozer to call the activity.

**Comment by markdenihan** [comment]
@SeanDuggan - 2.4 is supposed to be tomorrow. Is this going to be contained or will you move it to 2.5?

**Comment by SeanDuggan** [comment]
Moving to 2.5

**Comment by markdenihan** [comment]
Hey @SeanDuggan - 2.5 is the new 3.0. The Code freeze for three is due on Oct 16th. Will this make it or will we move this to 3.1?

**Comment by SeanDuggan** [comment]
Cutting it close but should make it.

**Comment by markdenihan** [comment]
Any update here @SeanDuggan ?

**Comment by SeanDuggan** [comment]
Aiming to close this at some point tonight.

**Comment by SeanDuggan** [comment]
This is taking much longer than I thought. Moving this to 3.1

**Comment by SeanDuggan** [comment]
Done!
