### ISSUE TITLE
Security Shepherd Development Environment Setup Video

### ISSUE THREAD

**Issue by SeanDuggan** [OWASP/SecurityShepherd#128]
I'm assigning this to you Napes, but I would like to get involved. if you can't do it let me know ASAP!

**Comment by markdenihan** [comment]
Assigning to @PhilDunphy as he said he can get this done relatively soon

**Comment by PhilDunphy** [comment]
This one is done. Just need to sprinkle some magic editing dust/sparkles on it. I will pass onto Mark tomorrow uncut and he can make editing decisions and I'll do the work. I couple the Dev environment with setting up local instance in the one video. Its 20 mins long and can definitely be chopped or not.

**Comment by markdenihan** [comment]
This is Complete. Check it out at https://youtu.be/uWk0NOSpyQc

Great Work @PhilDunphy
