### ISSUE TITLE
Security Shepherd Installation Video

### ISSUE THREAD

**Issue by SeanDuggan** [OWASP/SecurityShepherd#129]
Same as previous issue.

**Comment by markdenihan** [comment]
Assigning to @PhilDunphy as he said he can get this done relatively soon

**Comment by markdenihan** [comment]
This has indirectly been covered by @PhilDunphy here: https://youtu.be/uWk0NOSpyQc

I'm going to close this, but @SeanDuggan, if you had a vision for something else here; please reopen
