### ISSUE TITLE
Add Shepherd to OWASP Broken Web Applications

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#132]
BWA is an inactive OWASP project, which includes a lot of OWASP's Vulnerable applications and a number of vulnerable versions of certain services.

John said he'd look into the possibility of getting Shepherd added to it

**Comment by PhilDunphy** [comment]
Emailed Chuck Willis, waiting for reply

**Comment by markdenihan** [comment]
@PhilDunphy - You were saying you got a reply?

**Comment by PhilDunphy** [comment]
Yeah. Got some good info from him. Just emailed him back in regards to MySQL db and the question of does each app have its own instance

**Comment by PhilDunphy** [comment]
Got a reply from Chuck. He has done the work for us. He said he will put out a release candidate for the VM in the next week or so. He requested I put it through its paces. I guess we all could

**Comment by PhilDunphy** [comment]
Chcuk just released the new version of OWASPBWA with Security Sheperd within. It can be downloaded from here http://sourceforge.net/projects/owaspbwa/files/1.2rc1/ . Closing this issue
