### ISSUE TITLE
Window Adaptive UI

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#134]
If Somebody access' Shepherd via a mobile device, they get the desktop site. It would be great if they got a nice, simple mobile UI.

If this was implemented, users could copy keys from their android virtual devices and use the shepherd server from the device to complete levels. 

I think it would be good if the landing page was more "what is shepherd and why you should use it".

Leaving the Assignee Open on this. I'll take it up if needed.

**Comment by ismisepaul** [comment]
I created a website for my aunt a while back that uses HTML5 to display on both mobile and desktop depending on the screen size and it works really well.

Might be worth a look http://html5up.net/arcana just resize your window to see how it looks on a mobile -or view it on your mobile...

**Comment by SeanDuggan** [comment]
Thanks Paul! I will look into this.

**Comment by markdenihan** [comment]
I think it would be a better use of time if the current CSS was updated to adapt responsively to the size of the browser window. If Shepherd is not run in full screen, the experience is poor. Two Birds One Stone

Moving this into v2.5

**Comment by markdenihan** [comment]
I took the first step with this so that the UI now responds to the window size. Currently looks as normal above ~800 pixels, but folds together in anything less. 

The search box doesnt work very well in the responsive Css and some icons need to be updated to blend in with the new colours. If you guys can open bugs in this section of the UI i'll own em. 

Leaving this open until I fix the search box and icons

**Comment by markdenihan** [comment]
Search Box function has been updated to hold the Menu Bar open while the autocomplete box is also open. It will be easy to add to this so that we can support even smaller screen sizes

**Comment by markdenihan** [comment]
Included in commit 05385bd46a7f2a4919a28bc5d52cacd2340bc004
