### ISSUE TITLE
Create Dockerfile to build SecShep automatically

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#141]

**Comment by markdenihan** [comment]
I dont know if this will be any help for you Paul, but I wrote a script to turn a Clean Ubunutu Install and have Shepherd with SSL setup. 

(Kinda sucks you cant link files in issues) [Check It Out Here](https://raw.githubusercontent.com/markdenihan/owaspSecurityShepherd/989336e88e754c30eea579a79c9e9bf47b016d94/SecurityShepherdCore/setupFiles/shepherdTotalInstall.sh)

**Comment by markdenihan** [comment]
Whenever you've finished this @ismisepaul, We should put it here https://registry.hub.docker.com/repos/owasp/

**Comment by ismisepaul** [comment]
Okay I've finished this but... there's a bug in docker Ubuntu that's preventing me from starting Tomcat automatically. So when you run the Dockerfile you need to run both mysql and tomcat automatically while in the container.

If I could get people to test out the file see what people think before publishing?

I'm sending a mail to the group with the file

**Comment by ismisepaul** [comment]
Image is here https://registry.hub.docker.com/u/ismisepaul/security-shepherd/ closing and creating issue to move this to owasp repo. Dockerfile is created and image on docker hub
