### ISSUE TITLE
Review CheatSheet Entries

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#142]
Some of the Cheat Sheet Entries are out of date and currently incorrect.

One Example; 
CSRF Lesson cheatsheet says "'\<img src='url'/\>'", where the lesson now only accepts URLs

**Comment by McNeillChris9** [comment]
SQL Injection 1 cheatsheet says "  test'or'!='2@test.com   " is the correct answer, but actually causes a SQL syntax error.

Correct answer would be "  test'or''!='2@test.com   "   (extra ' to create empty string comparison)

**Comment by PhilDunphy** [comment]
Updated cheat sheet. Fixed issue raised by commenter above also in commit f2fcc6a925498cd60fcba599eae03fdd30768a5c
