### ISSUE TITLE
Move security-shepherd docker to owasp org on docker hub

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#148]
Currently here ~~https://registry.hub.docker.com/u/ismisepaul/security-shepherd/~~ https://hub.docker.com/r/ismisepaul/securityshepherd/

**Comment by markdenihan** [comment]
We'll do this when 153 is complete

**Comment by markdenihan** [comment]
Followed up with the Owner of the OWASP Repo in a couple of mails this week fyi

**Comment by DinisCruz** [comment]
@ismisepaul that page is now showing a 404

![image](https://cloud.githubusercontent.com/assets/656739/10118930/f11c6e0a-647e-11e5-9cf6-ba9db292efbd.png)

**Comment by DinisCruz** [comment]
Found it https://hub.docker.com/r/ismisepaul/securityshepherd/

**Comment by markdenihan** [comment]
I wasn't able to get the access I needed to add the docker image to the OWASP Repo, but Simon Bennett got it up for us!

https://hub.docker.com/r/owasp/security-shepherd/
