### ISSUE TITLE
Translation / Language Support

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#156]

**Comment by ismisepaul** [comment]
A functional translation method is in place with commit ecf139748f081e681c623a001bf3e78ef9c1a096 which can be expanded out to translate the entirety of Shepherd. However, there may be difficulties in parts as the application is not strictly MVC e.g. in dbProcs -> Getter.java the 'Get Next Challenge' button is generated instead of within a JSP.

**Comment by markdenihan** [comment]
I can look at changing how the Get Next Challenge button is returned, so it locally exists in the JSP rather than being generated by a class method.

Will this issue reoccur though in levels where responses are not contained in the JSP?

**Comment by markdenihan** [comment]
Spoke with Paul about how translations on data returned to the browser from ajax requests would be handled. He's going to look into it

**Comment by ismisepaul** [comment]
Okay looks like it's possible to translate Servlets so no need to change content over to JSP I'll add a commit with changes to Getter.java that will achieve this.

This code works for "Get Next Challenge Button":

`Locale.setDefault(new Locale("en"));
Locale locale = new Locale(lang);
ResourceBundle bundle = ResourceBundle.getBundle("i18n.text", locale);

+ "<div class='menuButton'>" + bundle.getString("getter.button.nextChallenge")+ "</div>" `

**Comment by markdenihan** [comment]
Ok thats awesome. So at this point we have the mechanism available for translation. Now we just need to go and implement serverside changes to point at prop files for words rather than the hardcoded versions, and write prop files for jsp? If that's the case how do you want to proceed @ismisepaul ? Do you want to close this issue and make new ones that work through the lessons first? They'd have the biggest bulk of text that would require translation? This seems a bit too big for one issue

**Comment by ismisepaul** [comment]
Yeah I'll close this and open an issue to translate the lessons as discussed this area is high priority for the players of the game. I've created a wiki on what to do - it's mainly a copy paste jobs replacing English strings with FMT markup and putting the English strings into .properties files. The people doing the actual translation can then create their own .properties file outlined in the wiki. 

https://github.com/OWASP/SecurityShepherd/wiki/Translating-Pages

The bones of it is included in commit 6ba129a38a238b0274e9f1428ce2e5c156f87909
