### ISSUE TITLE
Translation Support for Lessons in Security Shepherd

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#163]
The bones of this is in place under i18n/lessons/<various-lessons>

Wiki created on how to modify JSP and servlets for translation (https://github.com/OWASP/SecurityShepherd/wiki/Translating-Pages)

**Comment by markdenihan** [comment]
I've put the english files in for 5 of the lessons so far. I'll try to hit some more later tonight

**Comment by markdenihan** [comment]
renaming this issue for just covering the Language support in lessons. We can track the creation of specific language prop files with other issues. I've done another 5 or so lessons

**Comment by markdenihan** [comment]
@PhilDunphy Is going to Close out the Last Three Lessons

**Comment by markdenihan** [comment]
Lesson JSPs now support Translation. Time to hit the Lesson Servlets

**Comment by markdenihan** [comment]
All of the lesson Servlets have been modified to support translation
