### ISSUE TITLE
SQLI Challenge JSP/Servlet Translation Support

### ISSUE THREAD

**Issue by PhilDunphy** [OWASP/SecurityShepherd#174]
I will take these

**Comment by PhilDunphy** [comment]
Completed. Just need to test then will check in. Getting 500 on one of the levels.

**Comment by markdenihan** [comment]
500 errors from this kind of enhancement are typically due to your
ResourceBunde can't find the properties file, or can't find the key in the
properties file (typos in getString method)

On Sat, 29 Aug 2015 23:53 PhilDunphy <notifications@github.com> wrote:

> Completed. Just need to test then will check in. Getting 500 on one of the
> levels.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/174#issuecomment-136058903>
> .
>
-- 

Regards,

Mark Denihan

**Comment by PhilDunphy** [comment]
Tomcat console is not showing up and issues. I had similar issue with typos and and error showed in console but frame still rendered minus the bundle.getString(). I will fine tooth comb. Thanks for info Mark

**Comment by PhilDunphy** [comment]
Done. Commited in 6522ad05a6ec111bf7ab5a99279e13e32c2c43a3
