### ISSUE TITLE
Create Translation Support for SQL Injection Challenges

### ISSUE THREAD

**Issue by PhilDunphy** [OWASP/SecurityShepherd#176]

**Comment by markdenihan** [comment]
@PhilDunphy - I can see the i18n files there, but you havn't closed the issue. Arr you still testing or can this be closed out?

**Comment by PhilDunphy** [comment]
Checked in with 12a52cbedd3ec6fe8b965809895bad91beb6ac10 Have I got issue names wrong?

**Comment by markdenihan** [comment]
I think you're OK. The Jsps are easy enough to test. The servers can be more difficult because you have to test each logic flow. Just went though it with session management myself. A pain. Have you done this for sqli? If not I can give you a hand

**Comment by markdenihan** [comment]
@PhilDunphy - You're done here right?

**Comment by PhilDunphy** [comment]
Yeah done here Mark.
