### ISSUE TITLE
Upgrade Production to Beta

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#179]
Drop new War Files and some DB Updates. I'll take all the necessary updates from 2.4 and add them to an upgrade script for updating to 3.0

**Comment by markdenihan** [comment]
Completed this today. 

I've also got a Core Schema Upgrade Script that will bring a 2.4 database up to version 3. We'll need to track any more DB Changes we make and ensure they're included in the update script.

Check it out at SecurityShepherd/SecurityShepherdCore/setupFiles/updateCoreSchemaV2.4toV3.sql

**Comment by PhilDunphy** [comment]
Sweet. Working like a dream!!
