### ISSUE TITLE
InsecureData - database disk image is malformed

### ISSUE THREAD

**Issue by andrearievilo** [OWASP/SecurityShepherd#181]
When trying to query or even .dump the Members DB I get the following error:
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
/****** CORRUPTION ERROR *******/
/****** database disk image is malformed ******/
/****** ERROR: database disk image is malformed ******/
/****** CORRUPTION ERROR *******/
/****** database disk image is malformed ******/
/****** ERROR: database disk image is malformed ******/
/**** ERROR: (11) database disk image is malformed *****/
COMMIT;

Was able to bypass this by reading the raw and figuring out the key from it.

**Comment by SeanDuggan** [comment]
Thanks @andrearievilo Will fix this shortly.

**Comment by markdenihan** [comment]
@SeanDuggan is this the same as Issue #155 ?

**Comment by SeanDuggan** [comment]
Yup, it seems like writing the db files to the device on startup has caused a corruption somewhere. Initially, it looked like this problem was just with InsecureData2 but since that's not the case, InsecureData1 will also have this issue.

**Comment by andrearievilo** [comment]
I've attempted to extract Members from the apk package and then from the source however both of them have the same issue and the app seems to do a simple copy of the DB from assets to the device.

**Comment by SeanDuggan** [comment]
@andrearievilo That's right. The idea is to have the key contained within the DB stored within assets, when the app starts it copies this to the file system. With this method, there is no SQL in use on the App, since the challenge is focused on the storage of the data.

**Comment by SeanDuggan** [comment]
Fixed.

Players can now use sqlite to interact with insecure databases.
