### ISSUE TITLE
change the font of Chinese version

### ISSUE THREAD

**Issue by leishao2** [OWASP/SecurityShepherd#184]
could change the fond of Chinese version? it looks a bit strange.
for example: 复制/粘贴缓冲区高速缓存

**Comment by markdenihan** [comment]
Might be possible to set a preference. But I think some browsers/os
overwrite it anyway (Eg, open shepherd in Linux vs Widows. Different font)

What font would you like lei?

On Thu, 10 Sep 2015 17:44 lei shao <notifications@github.com> wrote:

> could change the fond of Chinese version? it looks a bit strange.
> for example: 复制/粘贴缓冲区高速缓存
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/184>.
>
-- 

Regards,

Mark Denihan

**Comment by markdenihan** [comment]
Would open Sans work? We could change the xss to that and then problem solved?

**Comment by markdenihan** [comment]
@leishao2 - Would open sans look ok for Chinese?

**Comment by leishao2** [comment]
I have read it online, for the different Operation System, the font could be different, for the Windows System, (微软雅黑：)Microsoft YaHei  is very popular, for OS X, (冬青黑体:) Hiragino Sans GB would be great.

**Comment by markdenihan** [comment]
So does that mean that the OS should be overwriting the font presented by
shepherd anyway?

On Thu, 24 Sep 2015 09:06 lei shao <notifications@github.com> wrote:

> I have read it online, for the different Operation System, the font could
> be different, for the Windows System, (微软雅黑：)Microsoft YaHei is very
> popular, for OS X, (冬青黑体:) Hiragino Sans GB would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/184#issuecomment-142974364>
> .
>
-- 

Regards,

Mark Denihan

**Comment by leishao2** [comment]
Hi Mark,

for what I investigate now, it does not matter on the different Operation System,  found the Chinese font setting up for Verse, like this: font-family: "Helvetica Neue", Helvetica Arial, "Lucida Grande", sans-serif. could just set something like that first, if we use css to make up the page. I will do more investigation when it is needed. ;) 
hopefully this can help.

Regards,
Lei

**Comment by markdenihan** [comment]
Yeah, if we change it there it will change for every language though. If
there is one font that suits all characters (helvetica?) in each language,
that would be easy.

If we need to have a font per language, not so easy, but I have a plan in
mind for that scenario ☺

On Mon, 28 Sep 2015 18:24 lei shao <notifications@github.com> wrote:

> Hi Mark,
>
> for what I investigate now, it does not matter on the different Operation
> System, found the Chinese font setting up for Verse, like this:
> font-family: "Helvetica Neue", Helvetica Arial, "Lucida Grande",
> sans-serif. could just set something like that first, if we use css to make
> up the page. I will do more investigation when it is needed. ;)
> hopefully this can help.
>
> Regards,
> Lei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/184#issuecomment-143811501>
> .
>
-- 

Regards,

Mark Denihan

**Comment by leishao2** [comment]
That is great, Mark! would like to know how it works!

 Regards,
Lei

**Comment by markdenihan** [comment]
Spoke with @leishao2, going to change the font to something like font-family: "Helvetica Neue", Helvetica Arial, "Lucida Grande", sans-serif. 

And we'll see if it's universally comfortable to read across the app

**Comment by markdenihan** [comment]
@leishao2 - I just updated the font to Helvetica Neue in the CSS in commit 5b24ec666e0a1027a20ec6128e7555bf7231cc4b, give it a look and see if it works out ok for Chinese Characters. If So, please close :)

**Comment by markdenihan** [comment]
@leishao2 - Are we good to close this? (I think the new font is awesome fyi)

**Comment by leishao2** [comment]
Hi Mark, I will close this issue, since they look great now.
