### ISSUE TITLE
Admin Actions Video Documentation

### ISSUE THREAD

**Issue by SeanDuggan** [OWASP/SecurityShepherd#192]

**Comment by PhilDunphy** [comment]
I'll pick this one up

**Comment by markdenihan** [comment]
Hows that going John?

**Comment by PhilDunphy** [comment]
I will definitely do it tomorrow night.

**Comment by markdenihan** [comment]
@PhilDunphy - When you get a chance can you upload that video / gimme it to upload? I'll link it off the Shepherd Wiki Then :)

**Comment by markdenihan** [comment]
@PhilDunphy Finished theses!

https://www.youtube.com/watch?v=sb8KQV6morY
https://www.youtube.com/watch?v=0jTWVLSGbPk
