### ISSUE TITLE
Create Mobile Setup Video

### ISSUE THREAD

**Issue by SeanDuggan** [OWASP/SecurityShepherd#193]

**Comment by markdenihan** [comment]
Hey @SeanDuggan - Can you send e the video to upload / link to put on the wiki?

**Comment by SeanDuggan** [comment]
Yeah, will have it ready either end of today or Saturday.

**Comment by SeanDuggan** [comment]
Done!

https://youtu.be/yppMkJRp4pk

More videos to follow.

**Comment by GohEeEn** [comment]
Hi @SeanDuggan, it seems like the youtube link above refering to an unavailable video now.
