### ISSUE TITLE
Mobile levels appearing under "Lessons" when "Web Application Only" is set

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#194]
The following mobile levels appear when "Web Application only" is selected;

* Content Provider Leakage
* Poor Authentication

These levels are also not affected when mobile only is selected

**Comment by markdenihan** [comment]
@SeanDuggan This is to do with the category list named mobileModuleCategoryHardcodedWhereClause at line 325 in Setter.java

I can fix it if you want, just assign me it

**Comment by markdenihan** [comment]
Fixed from commit cb88fc00a35d163f8000fa22cba856be334dd292
