### ISSUE TITLE
Side Menu Not Updating When Module Layout is Changed

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#206]
When an admin changes the module layout e.g. 'Enable Open Floor Mode' the side menu does not update. It is necessary to refresh the page.

**Comment by markdenihan** [comment]
This needs to be updated as well when modules are opened/closed

**Comment by markdenihan** [comment]
Im working on this atm, hoping to expand the way the CTF Menu refreshes to encompass the entire spectrum of floor plan refresh's

**Comment by markdenihan** [comment]
So I've done the bulk of the work here by taking the functionality from the CTF Menu refresh, cleaning it up a bit and making it modular in commit 73b0ab555b8f58f9c579444757c4ecb0a859ef0b. So all that needs to be done now is to take the Module Refresh function adapt to the current floor plan and return the correct menu for that floor plan.

Might look to extend this better refreshing to users when the floor plan changes... Confident this will be complete tomorrow at the Project Summit

**Comment by markdenihan** [comment]
From commit 6d720af94c1cee5281238d3ddcda3f8ef9149b58 onwards, when an Admin Manipulates the side bar menu in any way (Module Layout, Open/close Modules), their menu refreshes. Player Menu refreshes every time they complete a level. I'd like to make a function that would automatically update a players menu when it has changed from the server. A task for another day. I'll Make an issue for 3.1 for that.
