### ISSUE TITLE
Add integration with Travis CI (Continuous Integration)

### ISSUE THREAD

**Issue by michaelhidalgo** [OWASP/SecurityShepherd#219]
It would be great to integrate SecurityShepherd with Travis CI (https://travis-ci.org/) that way, every time there is a pull request, all test run before merging the code.

**Comment by markdenihan** [comment]
Yeah this would be awesome

**Comment by markdenihan** [comment]
Looks like @ismisepaul is working on this as part of #359

**Comment by ismisepaul** [comment]
@markdenihan we should add this as a step before merging etc. and then close this

**Comment by ismisepaul** [comment]
Before merging build must pass
