### ISSUE TITLE
Mobile Data Leakage Translation Support

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#229]
Making the issues so we can track the work. Please Pick up the issue if you can!

Just for the Challenge JSPs on the Shepherd Platform, not necessarily the mobile levels themselves for now

**Comment by SeanDuggan** [comment]
Done!

**Comment by markdenihan** [comment]
Reopening as Mobile Data Leakage 1 does not support localisation yet

**Comment by markdenihan** [comment]
Just discovered that there are hard coded strings in the Data leakage lesson as well. @SeanDuggan can you mend these?

**Comment by markdenihan** [comment]
Actually @SeanDuggan, turns out that was actually an orphaned file. I'll Do the challenge localisation to get it out of the way

**Comment by markdenihan** [comment]
Done
