### ISSUE TITLE
Test All Lessons/Challenges

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#247]
New Key Implementations and Localisation Support need to be re-verified as sound before we push 3.0 out

Hopefully we'll have this automated for 3.1

**Comment by markdenihan** [comment]
Tested all of the lessons at this point. Moving onto Challenges...

**Comment by markdenihan** [comment]
Just XSS and Session Management Challenges to Verify

**Comment by markdenihan** [comment]
Done!

**Comment by PhilDunphy** [comment]
Beast!!
