### ISSUE TITLE
docker pull doesn't work

### ISSUE THREAD

**Issue by iffy** [OWASP/SecurityShepherd#260]
Maybe I'm missing something, but the instructions on the README don't work for me:

```
$ docker pull owasp/security-shepherdUsing default tag: latest
Pulling repository docker.io/owasp/security-shepherd
Tag latest not found in repository docker.io/owasp/security-shepherd
```

**Comment by markdenihan** [comment]
Thanks @iffy for raising this.
@ismisepaul - Can you look into this please?

**Comment by ismisepaul** [comment]
Investigating in the mean time @iffy you can pull a 2.4 image from here https://hub.docker.com/r/ismisepaul/securityshepherd/

**Comment by ismisepaul** [comment]
Until we can work with the OWASP dockerhub I'm going to use https://hub.docker.com/r/ismisepaul/securityshepherd/ as the official place to grab shepherd on docker
