### ISSUE TITLE
Typo in welcome page after login as player

### ISSUE THREAD

**Issue by thomakj** [OWASP/SecurityShepherd#262]
After logging in as a player you hit a welcome page with this text: "Let's Get Started". 
In the second paragraph of the second section: there is a typo "Remember, the levels you are playing are sub applications. Keep the game play in these applications! Stay away from your session ID's! You'll just log yourself out _of_ you change them!"

"of" (the fourth last word) should be changed to "if".

**Comment by SeanDuggan** [comment]
Confirmed in https://github.com/OWASP/SecurityShepherd/blob/dev/SecurityShepherdCore/src/i18n/text.properties

Thanks for spotting that thomakj!

**Comment by SeanDuggan** [comment]
Issue resolved.
