### ISSUE TITLE
docker: Repository not found

### ISSUE THREAD

**Issue by wurstbrot** [OWASP/SecurityShepherd#264]
Hi,

I get the following message by trying to pull:
wb@wb-desktop:~$  docker pull owasp/security-shepherd 
Pulling repository owasp/security-shepherd
FATA[0002] Repository not found                         

For sure I see it on https://hub.docker.com/r/owasp/security-shepherd/, do you have any ideas?

Does the commit https://github.com/OWASP/SecurityShepherd/commit/2a2cb3d7c05973f9afd87fe850ff0fdbf0a7b3f2 may be forgot to change the description (in addition to the link?)

**Comment by ismisepaul** [comment]
You're right can you pull from this dockerhub instead (I've updated the readme to reflect this now)

docker pull ismisepaul/securityshepherd
