### ISSUE TITLE
Build does not work on Linux / MacOS X

### ISSUE THREAD

**Issue by vanderaj** [OWASP/SecurityShepherd#266]
The current ant build task assumes Windows. We should use environment variables to find the webapps folder. 

Please have a look at how other projects build to allow Eclipse local servers to work (i.e. direct debugging using a local tc server).

**Comment by vanderaj** [comment]
Hi guys,

I'm going to take on this one, I hope you don't mind. I'll test building under Windows, Mac and Linux before I check it back in. Is that okay?

**Comment by SeanDuggan** [comment]
Hi Andrew,

That shouldn't be a problem. Good luck!

**Comment by Matool13** [comment]
Am I understanding correctly, that in order to build successfully I should use Eclipse on Windows?   Ive been fighting with a custom build on Linux just using ant ending up with 500 errors.

/me wanders off to download Eclipse

**Comment by markdenihan** [comment]
Closing this while cleaning up the issues in github. This shouldn't be a problem with the last released Manual Pack. New Dev stream is built with maven and that's also been tested on Unix / Windows
