### ISSUE TITLE
Documentation for Docker still says start mongo

### ISSUE THREAD

**Issue by robotate** [OWASP/SecurityShepherd#275]
The documentation on https://hub.docker.com/r/ismisepaul/securityshepherd/ does not say to start Mongo(and in fact it is not installed in the image).

The README.md here still says to start mondod.

**Comment by ismisepaul** [comment]
So we have two branches on github one dev which contains the mongo level in docker and one master which does not. Unfortunately the dockerfile was not ready upon release of 3.0 so the Shepherd Master only contains the the 2.4 docker. The readme file and docker file on master reflect this. 

On docker hub you can see the two tags here seperating dev and master https://hub.docker.com/r/ismisepaul/securityshepherd/tags/

Dockerhub is linked with github and automatically pulls over both readme and dockerfile. I'm not sure why its taking one from dev and the other from master. Please use github for the correct instructions

Master https://github.com/OWASP/SecurityShepherd/tree/master
Dev https://github.com/OWASP/SecurityShepherd/tree/dev

If you want the docker image with the mongo levels you can pull from dev using the tag `docker pull ismisepaul/securityshepherd:dev`
