### ISSUE TITLE
docker does not work

### ISSUE THREAD

**Issue by shakahub** [OWASP/SecurityShepherd#281]
Cannot pull down image for security shepherd.

docker pull owasp/security-shepherd
Using default tag: latest
Pulling repository docker.io/owasp/security-shepherd
Tag latest not found in repository docker.io/owasp/security-shepherd

**Comment by ismisepaul** [comment]
Could you please pull the image from here https://hub.docker.com/r/ismisepaul/securityshepherd/

**Comment by ismisepaul** [comment]
closing this as its stated on the main page https://github.com/OWASP/SecurityShepherd#docker
