### ISSUE TITLE
Insecure Data Storage Challenge

### ISSUE THREAD

**Issue by Nirnias** [OWASP/SecurityShepherd#282]
Insecure Data Storage Challenge.

I think i must be missing something i am going through the challenges as a refresher, and i recall completing this challenge early last year. But now it seems either a file is missing, or i am doing something wrong.

The prompt says "To complete this challenge you'll need to use the InsecureData.apk app found in the Security Shepherd Android Virtual Machine (http://bit.ly/mobileShepherdVm). "

Yet navigating to that URL brings to download section with no files called that. Obviously i see the MobileShepherd one so i download that thinking its simply been renamed. See 4 apk files in there all called "ReverseEngineer.apk" "xxx2.apk", "xxx3.apk", "xxx4.apk". Again i think, ok simply renamed. Proceed to reverse engineer the first one, find the class and see the "string secret = The Key is xxxxxxxx" (Key obviously censored out, thats not actually the key).

When i try to submit the key, Security Shepherd tells me its incorrect. So i must be using the wrong APK file, yet i dont see where any other APK files are available to download for Security Shepherd.

Iv also opened the virtual image, and can see an "insecuredata" app, but clicking on it just goes to a page that says "The key is not here". 

Advice?

Update: I can see the key i mentioned above is for the Reverse Engineering challenge itself. So i do seem to just be missing the InsecureData.apk download.

**Comment by SeanDuggan** [comment]
Hi Nirnias,

Thanks for the feedback. When you start the challenge by loading up the instructions, there is a paragraph which outlines the issue. In this paragraph, details on how Apps store data insecurely are described. 

To complete this challenge you only need to Android VM, so once booted up and logged in, press ALT + F1 to get to the command line. Getting access to the command line gives you the control you need to get the key, it also simulates this challenge from the perspective of an attacker who would have root access. Generally, Apps can store data in multiple locations, SD Card, file system etc... When creating a database in Android, by default the path will be as such:

/data/data/<app package name>/database. 

In this example, you are using the command line to perform this action so you have all of the native linux commands at your disposal.

Once you get the key, press ALT + F7 to return to the GUI.

I am looking for as much feedback as possible and contributors! If you would like to join us in making vulnerable Apps let me know.

**Comment by Nirnias** [comment]
Thanks for the quick reply Sean, it seems i mixed up the challenge with another one.

I'v navigated to where the database should be located (/data/data/packagename/databasename). The first time i tried i did "ls" to see what was within the folder, and it came back with "Members" and "Members-Journal" i opened sqlite3 and tried ".open Members" but that did not work.

It's not fresh in my mind, but some combination of navigation, commands with grep and adb pull/adb shell eventually returned a lot of @ signs that ended with plain text with what looked like a password ending in 7's. *Internal sqee of yay i finally found it* but no, that didn't seem to get accepted as the key to pass the challenge :(

So went back to the start, went to databases and did ls -a, but this time found .databases and .dump within it (no Members). Opened sqlite3 again did .dump  and .databases but it just came back with whats in the image:
![image](https://cloud.githubusercontent.com/assets/3017149/13989956/634197d6-f10a-11e5-993d-5be56fe403d6.png)

Is the VM dynamic, that each time it is booted, that files/folders might be moved/renamed, etc? Would explain why i didnt find Members/Members-Journal again.
Am unsure how to go about "copying" the database contents from within the VM and moving them somewhere that i can inspect them with SQL DB Browser or something. But i feel like i am on the right track.

**Comment by SeanDuggan** [comment]
Not a problem!

Running the App should restore the database and you could use the "strings" command to view the contents of the database, since in this case, the size of the database is small.
