### ISSUE TITLE
Linux shell CLI in mobile shepherd vm

### ISSUE THREAD

**Issue by leishao2** [OWASP/SecurityShepherd#287]
Hi Sean,
I am trying to do the poor Authentication Lesson on mobile shepherd at the moment. by following the instructions in the Readme.txt file, which says press Alt + F1 to open the Linux shell CLI, it is not working for me. I have tried re-binding the Input Shortcut keys as well, but it is not actually working either. do you have any idea what the problem might be?
Thanks!
Regards,
Lei

**Comment by SeanDuggan** [comment]
Hi Lei,

Function + alt + f1 may work. Another way to get shell access is to connect via adb if you know the ip of the vm. In the platform tools folder in the android sdk open a command window and type adb devices, adb will show a list of android devices, once you get an ip type adb connect <address> followed by adb shell

**Comment by leishao2** [comment]
Thanks very much, Sean. 
it is brilliant, Fn +Alt +F1 works. I will try the second way later :).

Regards,
Lei
