### ISSUE TITLE
Naming Discrepancies

### ISSUE THREAD

**Issue by Nirnias** [OWASP/SecurityShepherd#288]
Hi,
I'v noticed this in 1 or 2 exercises, where the Challenge says "To complete this challenge you'll need to use the BrokenCrypto1.apk app found in the Security Shepherd Android Virtual Machine."

Yet when navigating to it's destination they are named differently.
In Corporal, the What is Mobile Broken Crypto? challenge says to use "BrokenCrypto.apk" that works. 
In Sergeant, the Mobile Broken Crypto 1 challenge says to use "BrokenCrypto1.apk" but this file/folder does not exist within the VM.
In Major, the Mobile Broken Crypto 2 challenge says to use "BrokenCrypto2.apk"
In Admiral, the Mobile Broken crypto 3 challenge says to use "BrokenCrypto4.apk".

I'v interpreted this as:
Corporal = BrokenCrypto.apk
Sergeant = BrokenCrypto2.apk
Major = BrokenCrypto3.apk
Admiral = BrokenCrypto4.apk

![image](https://cloud.githubusercontent.com/assets/3017149/15650561/60d1bf02-2671-11e6-8a8a-dbfecd49084c.png)
![image](https://cloud.githubusercontent.com/assets/3017149/15650600/97fce6aa-2671-11e6-80cc-303c7f7c529c.png)

Not a Major thing, but left me a bit confused for a few minutes as to which file to use :)

**Comment by SeanDuggan** [comment]
@Nirnias Thanks for spotting this, I believe the Reverse Engineering names need to be updated too. An updated Mobile VM will be released this week which will address this issue. I'll close this ticket once the VM is released.

**Comment by Nirnias** [comment]
Ah yes, that was the other one ReverseEngineering, i could not remember, but i just checked them, similiar as to above. 
Thanks Sean, i will grab the updated Mobile when it becomes available and ill truck on.

**Comment by SeanDuggan** [comment]
This has been fixed and the updated VM can be found among the downloads here: https://github.com/OWASP/SecurityShepherd/releases/tag/v3.0

Thanks again @Nirnias!
