### ISSUE TITLE
Configure to allow for the same solution key for all users?

### ISSUE THREAD

**Issue by vivida01** [OWASP/SecurityShepherd#291]
I'd like to use facebooks CTF platform in tandem with the OWASP Security Shepherd, is there a possibility of configuring the web app to allow for the same solution key to be generated for every player?

**Comment by markdenihan** [comment]
Configuration for this is something we can add. You could do it manually at
the moment by setting the hard-coded key flag to true for all levels

I Havnt tested that, but I expect it would stop the user specific key
function from running and you would just get the base result key

On Mon, 11 Jul 2016, 4:45 p.m. vivida01, <notifications@github.com> wrote:

> I'd like to use facebooks CTF platform in tandem with the OWASP Security
> Shepherd, is there a possibility of configuring the web app to allow for
> the same solution key to be generated for every player?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/291>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADUqniip405Iyblqte-scZ0nRODOjxEIks5qUmUJgaJpZM4JJgI6>
> .
>
-- 

Regards,

Mark Denihan

**Comment by vivida01** [comment]
Thanks so much for the quick response! Sorry to ask, but can you provide
some additional instruction for how to go about the manual change?

**Comment by vivida01** [comment]
Let me be more specific. After I have updated the hardcoded key flag to
true, is there anything additional I would need to do?

**Comment by markdenihan** [comment]
I don't think so... It should just work. As I said though it hasn't been
tested to operate like this before

On Mon, 11 Jul 2016, 5:50 p.m. vivida01, <notifications@github.com> wrote:

> Let me be more specific. After I have updated the hardcoded key flag to
> true, is there anything additional I would need to do?
>
> On Mon, Jul 11, 2016 at 11:53 AM, Daniel Vivio <daniel.vivio@nielsen.com>
> wrote:
>
> > Thanks so much for the quick response! Sorry to ask, but can you provide
> > some additional instruction for how to go about the manual change?
> >
> > On Mon, Jul 11, 2016 at 11:48 AM, Mark Denihan <notifications@github.com
> >
> > wrote:
> >
> >> Configuration for this is something we can add. You could do it manually
> >> at
> >> the moment by setting the hard-coded key flag to true for all levels
> >>
> >> I Havnt tested that, but I expect it would stop the user specific key
> >> function from running and you would just get the base result key
> >>
> >> On Mon, 11 Jul 2016, 4:45 p.m. vivida01, <notifications@github.com>
> >> wrote:
> >>
> >> > I'd like to use facebooks CTF platform in tandem with the OWASP
> Security
> >> > Shepherd, is there a possibility of configuring the web app to allow
> for
> >> > the same solution key to be generated for every player?
> >> >
> >> > —
> >> > You are receiving this because you are subscribed to this thread.
> >> > Reply to this email directly, view it on GitHub
> >> > <https://github.com/OWASP/SecurityShepherd/issues/291>, or mute the
> >> thread
> >> > <
> >>
> https://github.com/notifications/unsubscribe/ADUqniip405Iyblqte-scZ0nRODOjxEIks5qUmUJgaJpZM4JJgI6
> >> >
> >> > .
> >> >
> >> --
> >>
> >> Regards,
> >>
> >> Mark Denihan
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231776046
> >,
> >> or mute the thread
> >> <
> https://github.com/notifications/unsubscribe/AMDFgU6F9ZAoXEJsMP5cstH1bg77KXUlks5qUmXAgaJpZM4JJgI6
> >
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231794088>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADUqnhmWj3p4Wlh8Jh1_Cywn3RYTvuC7ks5qUnRrgaJpZM4JJgI6>
> .
>
-- 

Regards,

Mark Denihan

**Comment by vivida01** [comment]
Thanks Mark.

Unfortunately it's still creating unique keys after updating the
hardcodedkey flag to 1. Any other ideas you might have would be much
appreciated.

**Comment by markdenihan** [comment]
Aha, so we must only use that hardcoded key Value for key checking. We'll
have to make an issue to update the key returns to follow the same practise
as the key checks

On Mon, 11 Jul 2016, 7:24 p.m. vivida01, <notifications@github.com> wrote:

> Thanks Mark.
>
> Unfortunately it's still creating unique keys after updating the
> hardcodedkey flag to 1. Any other ideas you might have would be much
> appreciated.
>
> On Mon, Jul 11, 2016 at 12:54 PM, Mark Denihan <notifications@github.com>
> wrote:
>
> > I don't think so... It should just work. As I said though it hasn't been
> > tested to operate like this before
> >
> >
> > On Mon, 11 Jul 2016, 5:50 p.m. vivida01, <notifications@github.com>
> wrote:
> >
> > > Let me be more specific. After I have updated the hardcoded key flag to
> > > true, is there anything additional I would need to do?
> > >
> > > On Mon, Jul 11, 2016 at 11:53 AM, Daniel Vivio <
> daniel.vivio@nielsen.com
> > >
> > > wrote:
> > >
> > > > Thanks so much for the quick response! Sorry to ask, but can you
> > provide
> > > > some additional instruction for how to go about the manual change?
> > > >
> > > > On Mon, Jul 11, 2016 at 11:48 AM, Mark Denihan <
> > notifications@github.com
> > > >
> > > > wrote:
> > > >
> > > >> Configuration for this is something we can add. You could do it
> > manually
> > > >> at
> > > >> the moment by setting the hard-coded key flag to true for all levels
> > > >>
> > > >> I Havnt tested that, but I expect it would stop the user specific
> key
> > > >> function from running and you would just get the base result key
> > > >>
> > > >> On Mon, 11 Jul 2016, 4:45 p.m. vivida01, <notifications@github.com>
> > > >> wrote:
> > > >>
> > > >> > I'd like to use facebooks CTF platform in tandem with the OWASP
> > > Security
> > > >> > Shepherd, is there a possibility of configuring the web app to
> allow
> > > for
> > > >> > the same solution key to be generated for every player?
> > > >> >
> > > >> > —
> > > >> > You are receiving this because you are subscribed to this thread.
> > > >> > Reply to this email directly, view it on GitHub
> > > >> > <https://github.com/OWASP/SecurityShepherd/issues/291>, or mute
> the
> > > >> thread
> > > >> > <
> > > >>
> > >
> >
> https://github.com/notifications/unsubscribe/ADUqniip405Iyblqte-scZ0nRODOjxEIks5qUmUJgaJpZM4JJgI6
> > > >> >
> > > >> > .
> > > >> >
> > > >> --
> > > >>
> > > >> Regards,
> > > >>
> > > >> Mark Denihan
> > > >>
> > > >> —
> > > >> You are receiving this because you authored the thread.
> > > >> Reply to this email directly, view it on GitHub
> > > >> <
> > >
> >
> https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231776046
> > > >,
> > > >> or mute the thread
> > > >> <
> > >
> >
> https://github.com/notifications/unsubscribe/AMDFgU6F9ZAoXEJsMP5cstH1bg77KXUlks5qUmXAgaJpZM4JJgI6
> > > >
> > > >> .
> > > >>
> > > >
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231794088
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ADUqnhmWj3p4Wlh8Jh1_Cywn3RYTvuC7ks5qUnRrgaJpZM4JJgI6
> > >
> >
> > > .
> > >
> > --
> >
> > Regards,
> >
> > Mark Denihan
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231795236
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AMDFgTQPXgZyRyLdq8zwSY9fN28xiGpYks5qUnVYgaJpZM4JJgI6
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/SecurityShepherd/issues/291#issuecomment-231821105>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADUqnkUAosBM2PH_kO-V0B-VaL2lIpBQks5qUoppgaJpZM4JJgI6>
> .
>
-- 

Regards,

Mark Denihan

**Comment by vivida01** [comment]
I closed this issue and opened up a new one as you recommended. Thanks
again for your help on this.
