### ISSUE TITLE
Mobile challenge showing up when Web App only levels open

### ISSUE THREAD

**Issue by rtteal** [OWASP/SecurityShepherd#295]
The below Mobile challenge showed up for me when Web App levels only were opened.  I am using the docker image.

moduleId = 0cdd1549e7c74084d7059ce748b93ef657b44457
moduleName = Poor Authentication
moduleType = lesson
moduleCategory = Mobile Poor Authentication
moduleHash = 77777b312d5b56a17c1f30550dd34e8d6bd8b037f05341e64e94f5411c10ac8e

**Comment by SeanDuggan** [comment]
I'm seeing this too, but for another mobile lesson. Will look into it further. Thanks for reporting!

**Comment by SeanDuggan** [comment]
Inital issue reported has been fixed in dev, new issue discovered fixed in 904e70f
