### ISSUE TITLE
Closed challenges, can view and post results (and get points)

### ISSUE THREAD

**Issue by layderv** [OWASP/SecurityShepherd#311]
It's possible to get a closed challenge, use it and post the results to get points. I've managed to get this to work only once after any reboot. 

How to do it: 

- get the path of a closed challenge (eg. by opening it and intercepting the request with Burp; by issuing `ls /var/lib/tomcat7/webapps/ROOT/challenges` on the VM, ..) and its moduleId (if intercepting, it's in the first POST /getModule)
- log in as a normal user
- start intercepting with Burp
- click on any open challenge 
- forward the POST /getModule
- change the GET path to the closed challenge (/challenges/xyz.jsp)
- complete the challenge
- when submitting the key, change the moduleId parameter to the one saved before

I think in the first POST /getModule there's a check to see if the requested module can be accessed (that's why you should forward it, requesting an open challenge), but then it returns the path of the challenge and the next (GET) request is trusted

**Comment by markdenihan** [comment]
This looks like a problem when using Security Shepherd Stock Challenges as the hashed names of the JSP files are available on GitHub, along with their module Ids

We need to at least add a check that Modules are open before continuing in SolutionSubmit.java

Not sure about adding a check before presenting the moduleHash.jsp page, as these levels have no knowledge of their moduleId I believe
