### ISSUE TITLE
CSRF 2 not showing user ID

### ISSUE THREAD

**Issue by misoxxx** [OWASP/SecurityShepherd#314]
Hi,
I'm playing the shepherd right now, got till CSRF 2 but cannot continue because it doesn't show me my ID that should be incremented. Is this a bug? I watched a [video](https://www.youtube.com/watch?v=8mlY4ob757s), where it clearly shows the user id.
![Screenshot](https://user-images.githubusercontent.com/11175305/32993648-724dd8b4-cd5b-11e7-8e66-1840a490eb06.png)
Thanks.

**Comment by ricardojcampo** [comment]
Hello @misoxxx,

I had the same issue and I got no reply from these guys, the id is the same as the one from the previous exercise. Just use that one and it works. 

Hope this helps

Ric

**Comment by misoxxx** [comment]
Thanks!

Michal
