### ISSUE TITLE
Dockerfile Java Alternatives

### ISSUE THREAD

**Issue by MNWPRO** [OWASP/SecurityShepherd#316]
Dockerfile   
here is  a  error
apt-get install -y oracle-java7-installer --force-yes && \ 
can i   change it  to   openjdk-7   or  others？

**Comment by ismisepaul** [comment]
You could take the dockerfile from here https://hub.docker.com/r/ismisepaul/securityshepherd/~/dockerfile/

Change the line yourself if you wanted to try it. But at the moment there is no option to change the Java

**Comment by ismisepaul** [comment]
@MNWPRO I'm closing, feel free to open if you have any other queries on this.
