### ISSUE TITLE
Where I stand Scoreboard

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#322]
As a user
I can see a real time scoreboard that
shows my score, and the scores of the n users before me and n users behind me

*Acceptance Criteria*
- [ ] The Main Scoreboard has the option to switch to "Where I stand" view if My username is in the list
- [ ] The Where I stand View has the option to switch back to the main scoreboard
- [ ] The Where I Stand scoreboard shows up to n players who have scores higher than mine and up to n players who have (Where n makes sense for the UI to look good)
- [ ] If I am First the Where I stand board shows up to 2*n players after me (If I'm 2nd it shows up to (2*n)-1 players after me (If the number of  players on the board allows that many))
- [ ] If I am last place the Where I stand board shows 2*n players before me (If the number of  players on the board allows that many)
- [ ] My score bar is highlighted a different color from the other players
- [ ] The Where I stand scoreboard updates regularly

**Comment by cosmin91ro** [comment]
How is this feature different than the actual scoreboard?

**Comment by cosmin91ro** [comment]
Thanks for clarification, @ismisepaul

**Comment by markdenihan** [comment]
I added Acceptance Criteria to add further explanation of how this feature would work
