### ISSUE TITLE
Add Support for MySQL Server >8.0.4

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#361]
The default authentication plugin for MySQL server has changed from mysql_native_password to caching_sha2_password

When trying to connect to a MySQL server >8.0.4 the following error is observed when in the logs from the setup page;

`FATAL   Unable to create database connection: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.`

-WORKAROUND
ALTER USER 'student'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass123';

**Comment by etnoy** [comment]
It is possible that #514 fixes this as it doesn't use SHA2 from mysql

**Comment by ismisepaul** [comment]
#734 closes this issue
