### ISSUE TITLE
MySQL scripts don't execute due to syntax error

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#365]
Through a recent change to the mysql scripts (removing the delimiters for use with Java) they no longer run due to a syntax error;

`ERROR 1064 (42000) at line 141: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3`

For use in docker these scripts need to be in a format that they can be run in MySQL / command line

**Comment by markdenihan** [comment]
They were changed by @gbena so they could work over a JDBC Connection. I'll Add the custom deliminator statements in comments so you can sed the file so that they're back for CLI execution and this continues to work for JDBC

**Comment by markdenihan** [comment]
Can't Start this until #363 is merged

**Comment by ismisepaul** [comment]
@markdenihan that looks good, yeah if you add them to comments I can easily copy out those sql files and modify them with sed
