### ISSUE TITLE
Session Management challenge 1 is bugged

### ISSUE THREAD

**Issue by mromulus** [OWASP/SecurityShepherd#383]
EDIT: Line of Code to basically the answer was here

has incorrect answer for solution - `base64beforeEquals` decodes to `userRole=notTheRightRole` 

It should be changed to `base64beforeEquals==`, corresponding to `userRole=theRightRole`

**Comment by markdenihan** [comment]
Hey, You're correct that is the correct solution with the padding. We try to keep correct solutions out of github tickets so they're not indexed, fyi... So I've updated your comment so its sans the answers

When you submit the correct solution (With the padding) you will be given the result key to get the points for the level. Only reasonable way somebody would submit it without the padding is if they manually went to that line in the servlet source code, copied it and tried it in their browser. It will also work. The cheat sheet for this level also includes the padding

I just tested this again on 3.0 and the current dev branch and the correct answer with the padding and it results in the answer being returned. 

There is some weird behavior where the padding gets dropped from tomcat that we looked into a long time ago, but it does not leave the challenge with any bug. See #220 

Closing this as invalid

**Comment by mromulus** [comment]
Thanks for looking into it - I looked at the source code after I could not figure out what I was doing wrong - the same solution worked with a previous version of shepherd I had tested before. I am currently replicating the issue with up-to-date dev branch, running with docker - it does not seem to work with padding for me.

I'll attach the relevant section of the log for info:
```
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:43,894 [https-openssl-nio-8443-exec-9] (SessionManagement1.java:74) - Session Management Challenge One servlet accessed by: admin
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:43,894 [https-openssl-nio-8443-exec-9] (SessionManagement1.java:89) - Cookie value: base64defaultvalue
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:43,895 [https-openssl-nio-8443-exec-9] (SessionManagement1.java:105) - Challenge Not Complete
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:43,896 [https-openssl-nio-8443-exec-9] (SessionManagement1.java:129) - Outputting HTML
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:56,186 [https-openssl-nio-8443-exec-5] (SessionManagement1.java:74) - Session Management Challenge One servlet accessed by: admin
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:56,187 [https-openssl-nio-8443-exec-5] (SessionManagement1.java:89) - Cookie value: base64beforeEquals==
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:56,188 [https-openssl-nio-8443-exec-5] (SessionManagement1.java:105) - Challenge Not Complete
secshep_tomcat | DEBUG admin at 172.18.0.1 from ?.?.?.? @ 14 Sep 08:28:56,188 [https-openssl-nio-8443-exec-5] (SessionManagement1.java:129) - Outputting HTML
``` 

It seems like maybe the method you mention in the PR, `theCookie.getValue()` is not stable across some platforms (it's being logged by `log.debug("Cookie value: " + theCookie.getValue());`)

**Comment by markdenihan** [comment]
@ismisepaul Can you check this in the docker. It's possible that tomcat alpine is processing this differently than tomcat7/8/8.5

**Comment by ismisepaul** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/912403/45545139-56803e00-b811-11e8-89c8-7198ccbc8f17.png)

Tomcat docker info
```
bash-4.4# java -cp /usr/local/tomcat/lib/catalina.jar org.apache.catalina.util.ServerInfo
Server version: Apache Tomcat/8.5.32
Server built:   Jun 20 2018 19:50:35 UTC
Server number:  8.5.32.0
OS Name:        Linux
OS Version:     4.4.0-134-generic
Architecture:   amd64
JVM Version:    1.8.0_171-b11
JVM Vendor:     Oracle Corporation
```

**Comment by markdenihan** [comment]
@mromulus is right. Looks like cookie.getValue() is a little unstable when it comes to padding and it looks like tomcat 8.5 (What the new docker image will use) will return the padding as well - Breaking the level. However there is no problem if instead of checking for a specific base64 encoded value; Decode the cookie and check if it is equal to the value we expect.

This implementation is how other levels treat user submitted base64 in most places, but I'll make a ticket to make sure there are no other instances before we release 3.1.

This implementation will not break previous deployments and will work on tomcat 7, 8 and 8.5

**Comment by markdenihan** [comment]
Thanks @mromulus for catching that before we release 3.1!
