### ISSUE TITLE
Don't zip the VM file

### ISSUE THREAD

**Issue by Samuel-BF** [OWASP/SecurityShepherd#449]
Hi there,

Thanks for such a useful project. The VMs in [releases](https://github.com/OWASP/SecurityShepherd/releases/) are zipped, which is unnecessary as the OVA file format already compress disks. So the difference between the zipped and the uncompressed file is negligible (and, if I recall, the zipped file weighs slightly more).

Also : it's not possible to unzip them with `unzip` utility on Linux (you have to install p7zip), which makes them less convenient for deployment directly into hypervisors (XenServer, for example, does not provide p7zip by default, you have to download it separately which is not recommended ... but for xenserver you also have the problem that from the cli you can only import XVA files...).

**Comment by markdenihan** [comment]
Saved us >50mb I think to compress and even then it's too big. 

We're going to have to build it on something like alpine instead in the future.

I'll see if github will allow the uncompressed VM up in the release files

**Comment by markdenihan** [comment]
I uploaded the OVA, but ti seems to be appearing and disheartening from the Releases Page. Maybe Github is scanning it.

**Comment by markdenihan** [comment]
It's there now, unzipped

**Comment by markdenihan** [comment]
FYI this has been removed and replaced with a new zip. We re-zipped it with deflate instead of instead of LZMA so that any unzipper can unzip it. 

Need to zip it to include the read me because people were complaining about not knowing how to log in!
