### ISSUE TITLE
owaspSecurityShepherd_v3.1_ManualPack.zip might be corrupted

### ISSUE THREAD

**Issue by rickysunkwokshing** [OWASP/SecurityShepherd#453]
new user, i got an error when try to open the readme.txt within the owaspSecurityShepherd_v3.1_ManualPack.zip.

**Comment by markdenihan** [comment]
I think this is because we used LZMA compression for that zip file to try maximize the compression ratio. Looks like some common unzippers don't have this. I'll recompress with a common method as we're only saving ~30mb using LZMA

What did you use to unzip?

**Comment by markdenihan** [comment]
Updated the VM and the Manual pack to use Deflate instead of LZMA so now all unzippers will work by default

Available from https://github.com/OWASP/SecurityShepherd/releases/tag/v3.1

Thanks @rickysunkwokshing for raising the issue
