### ISSUE TITLE
mvn -Pdocker install fails on OS X due to sed backslash.

### ISSUE THREAD

**Issue by Deseao** [OWASP/SecurityShepherd#461]
I was unable to get the maven target to run correctly on the dev branch, so I checked out `master` and was able to start the db and webserver. However, something is still broken. When I attempt to login as admin I get an invalid username or password message and see this in the tomcat logs:

`secshep_tomcat | DEBUG 172.19.0.1 from ?.?.?.? @ 02 Jan 22:17:35,310 [https-openssl-nio-8443-exec-2] (Getter.java:70) - $$$ Getter.authUser $$$
secshep_tomcat | DEBUG 172.19.0.1 from ?.?.?.? @ 02 Jan 22:17:35,312 [https-openssl-nio-8443-exec-2] (Getter.java:71) - userName = admin
secshep_tomcat | DEBUG 172.19.0.1 from ?.?.?.? @ 02 Jan 22:17:35,349 [https-openssl-nio-8443-exec-2] (Getter.java:80) - Gathering userFind ResultSet
secshep_tomcat | ERROR 172.19.0.1 from ?.?.?.? @ 02 Jan 22:17:35,352 [https-openssl-nio-8443-exec-2] (Getter.java:153) - Login Failure: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE core.userFind does not exist
secshep_tomcat | DEBUG 172.19.0.1 from ?.?.?.? @ 02 Jan 22:17:35,353 [https-openssl-nio-8443-exec-2] (Getter.java:158) - $$$ End authUser $$$`

I would really appreciate guidance on how to get this running correctly in docker.

**Comment by Deseao** [comment]
Here's what happens when I run `mvn -Pdocker clean install -DskipTests` on the `dev` branch:

`
[INFO] --- exec-maven-plugin:1.6.0:exec (convert-sql-scripts) @ owaspSecurityShepherd ---
sed: 1: "docker/mysql/coreSchema ...": extra characters at the end of d command
sed: 1: "docker/mysql/moduleSche ...": extra characters at the end of d command
sed: 1: "docker/mysql/coreSchema ...": extra characters at the end of d command
sed: 1: "docker/mysql/moduleSche ...": extra characters at the end of d command
sed: 1: "docker/mysql/coreSchema ...": extra characters at the end of d command
sed: 1: "docker/mysql/moduleSche ...": extra characters at the end of d command
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
...
`

**Comment by Deseao** [comment]
Looks like I missed an error when running the install target on master as well, so the original error is almost certainly caused by that failing.

```
[INFO] --- maven-antrun-plugin:1.8:run (copy-db-scripts) @ owaspSecurityShepherd ---
[INFO] Executing tasks

main:
     [echo] ANT TASK - Copying database files and modifying for use with mysql
     [copy] Copying 3 files to /Users/ahaynes/git/github/SecurityShepherd/docker/mysql
     [copy] Copying 1 file to /Users/ahaynes/git/github/SecurityShepherd/docker/mongo
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
[INFO] Executed tasks
[INFO]
```

With DEBUG output: 
```
main:
     [echo] ANT TASK - Copying database files and modifying for use with mysql
fileset: Setup scanner in dir /Users/ahaynes/git/github/SecurityShepherd/src/main/resources/database with patternSet{ includes: [*.sql, *.sql] excludes: [] }
     [copy] Copying 3 files to /Users/ahaynes/git/github/SecurityShepherd/docker/mysql
     [copy] Copying /Users/ahaynes/git/github/SecurityShepherd/src/main/resources/database/coreSchema.sql to /Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql
     [copy] Copying /Users/ahaynes/git/github/SecurityShepherd/src/main/resources/database/moduleSchemas.sql to /Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql
     [copy] Copying /Users/ahaynes/git/github/SecurityShepherd/src/main/resources/database/updatev3_0tov3_1.sql to /Users/ahaynes/git/github/SecurityShepherd/docker/mysql/updatev3_0tov3_1.sql
fileset: Setup scanner in dir /Users/ahaynes/git/github/SecurityShepherd/src/database with patternSet{ includes: [*.js, *.js] excludes: [] }
     [copy] Copying 1 file to /Users/ahaynes/git/github/SecurityShepherd/docker/mongo
     [copy] Copying /Users/ahaynes/git/github/SecurityShepherd/src/database/mongoSchema.js to /Users/ahaynes/git/github/SecurityShepherd/docker/mongo/mongoSchema.js
     [exec] Current OS is Mac OS X
     [exec] Executing 'sed' with arguments:
     [exec] '-i'
     [exec] 's/-- DELIMITER \$\$/DELIMITER \$\$/g'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'sed' with arguments:
'-i'
's/-- DELIMITER \$\$/DELIMITER \$\$/g'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'

The ' characters around the executable and arguments are
not part of the command.
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
     [exec] Current OS is Mac OS X
     [exec] Executing 'sed' with arguments:
     [exec] '-i'
     [exec] 's/-- \$\$/\$\$/g'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'sed' with arguments:
'-i'
's/-- \$\$/\$\$/g'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'

The ' characters around the executable and arguments are
not part of the command.
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
     [exec] Current OS is Mac OS X
     [exec] Executing 'sed' with arguments:
     [exec] '-i'
     [exec] 's/-- DELIMITER \;/DELIMITER \;/g'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
     [exec] '/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'sed' with arguments:
'-i'
's/-- DELIMITER \;/DELIMITER \;/g'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/coreSchema.sql'
'/Users/ahaynes/git/github/SecurityShepherd/docker/mysql/moduleSchemas.sql'

The ' characters around the executable and arguments are
not part of the command.
     [exec] sed: 1: "/Users/ahaynes/git/gith ...": command a expects \ followed by text
     [exec] Result: 1
[INFO] Executed tasks
```

**Comment by ismisepaul** [comment]
This seems to be a known problem with sed on Linux vs OSX. I don't have a mac to test this out at the minute but could you try what is suggested [here](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux/14813278#14813278);



You'll have to modify the  [convert-sql-scripts.sh](https://github.com/OWASP/SecurityShepherd/blob/dev/docker/scripts/convert-sql-scripts.sh)

**Comment by Deseao** [comment]
I've modified the script and it's working great for me. Could you check that it doesn't affect the Linux installation? Also I have no idea what unit tests should be run, etc. https://github.com/OWASP/SecurityShepherd/pull/462
