### ISSUE TITLE
SQL Injection Challenge Two: accepts invalid e-mail addresses

### ISSUE THREAD

**Issue by reruesch** [OWASP/SecurityShepherd#470]
SQL Injection Challenge Two accepts invalid e-mail addresses, e.g. `x@x'or'1'='1`
It seems that the currently used version 1.4 of the JavaMail library is erroneously accepting this input string as valid email address.

**Solution**: use version 1.4.7 of JavaMail [(https://mvnrepository.com/artifact/javax.mail/mail/1.4.7)](https://mvnrepository.com/artifact/javax.mail/mail/1.4.7)

BTW: code of method `isValidEmailAddress()` in `utils.Validate.java` does not follow best practice of "Security by Default", it starts with `result = true;`

**Comment by markdenihan** [comment]
This challenge is intentionally vulnerable

**Comment by reruesch** [comment]
I'm sorry, but you missed my point.
The challenge is to craft an attack that respects the format of a valid e-mail address. Thus my students don't understand that such bad solutions are accepted by this challenge! 
Furthermore I gave you the solution to this issue, so please reconsider this.

**Comment by markdenihan** [comment]
Good point! Lets try update the dependency to 1.4.7 and see if the cheat sheet solution continues to work.

The "Security by default" because result = true is a non issue.

**Comment by reruesch** [comment]
I changed to version 1.4.7 on my SecurityShepherd server is use for lab work with my students. Works like a charm.
