### ISSUE TITLE
SQL Injection 5 - add error messages

### ISSUE THREAD

**Issue by reruesch** [OWASP/SecurityShepherd#471]
If students order 9999 trolls, the answer says that the order succeeded. This is misleading.

There should be some kind of an error message if (after amount validation, before subtracting couponCode discount) all amount values are 0.

**Comment by markdenihan** [comment]
@reruesch Seems like it would be confusing if the order always failed unless you had gotten everything for free while you prob the functionality. We can add a message that says "You havn't solved this challenge yet" though
