### ISSUE TITLE
SecurityShepherd.auth doesn't exist

### ISSUE THREAD

**Issue by wonderphil** [OWASP/SecurityShepherd#476]
Hi all,

I have just completed the manual setup on ubuntu and when I get to the DB config web page, it states i need to get SecurityShepherd.auth from

```
/opt/tomcat//conf/SecurityShepherd.auth
```

But this file doesnt exist.

Am I doing something wrong here?

**Comment by markdenihan** [comment]
Can you attach tomcat logs?

**Comment by wonderphil** [comment]
Hey mark,

Sorry didnt even thing at looking at tomcat logs.  Either way Ive got home and restarted tomcat again and now the file is there.

So will close this.

Thanks

Phil
