### ISSUE TITLE
What is the default password to login into virtual machine in latest release 3.1

### ISSUE THREAD

**Issue by vivekj2** [OWASP/SecurityShepherd#478]

**Comment by BruceMacD** [comment]
user: `securityshepherd`
pass: `shepherd3.1`

The default username and password are specified in the `readme.txt` file included with the virtual machine image.

**Comment by kurohat** [comment]
password is not working for me. pls help

**Comment by markdenihan** [comment]
If the default password isn't working it must have been changed in that
deployment. If you're the admin you will have to find a way around it or
just deploy a fresh vm
