### ISSUE TITLE
Sevlet mapping is missing for Insecure Cryptographic Storage Home Made Keys challenge

### ISSUE THREAD

**Issue by abhinav-k** [OWASP/SecurityShepherd#480]
When user tries to submit solution to `Insecure Cryptographic Storage Home Made Keys` challenge, a post request is made to URL: `/challenges/9e5ed059b23632c8801d95621fa52071b2eb211d8c044dde6d2f4b89874a7bc4` to validate the submitted solution and to return the result key for the challenge if the solution is correct. As servlet mapping for that url is missing in `web.xml`, the post request is returning 404.

**Comment by abhinav-k** [comment]
Related: https://github.com/OWASP/SecurityShepherd/pull/378/files#diff-411d1a9625fc3f5d5be34d116942f6caL1197

**Comment by markdenihan** [comment]
Thanks @abhinav-k
