### ISSUE TITLE
Copy to clipboard does not work as intended for challenge " Insecure Cryptographic Storage Home Made Keys"

### ISSUE THREAD

**Issue by abhinav-k** [OWASP/SecurityShepherd#482]
![image](https://user-images.githubusercontent.com/5916235/58756510-73ec5980-84bf-11e9-8133-68eb26ee50e4.png)
In this challenge, we have multiple text areas to display user specific solution one for each contest and each text areas has a button to copy that key as shown in above image. All these text areas corresponds to same common id called `#theKey` .  Copy to clipboard button is wired to copy the content of textarea with id `#theKey` to clipboard.  As ids are not unique on this webpage, the copy to clipboard button always copies contents of first text area instead of copying its corresponding text area.

**Comment by markdenihan** [comment]
Thanks @abhinav-k
