### ISSUE TITLE
The hint in the "SQL Injection Escaping Challenge" is wrong

### ISSUE THREAD

**Issue by jmanico** [OWASP/SecurityShepherd#485]
The hint in the SQL Injection Escaping Lab is...

SELECT * FROM customers WHERE customerId ="$DATA";

This is not correct, I believe. I think it should be single quotes.

SELECT * FROM customers WHERE customerId ='$DATA';

This has thrown off a lot of students, a fix would be great!

**Comment by markdenihan** [comment]
Fix is in the Dev stream, will be in 3.2

**Comment by jmanico** [comment]
👍🏼👍🏼

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805
