### ISSUE TITLE
SQL Injection Lesson java.sql.SQLException

### ISSUE THREAD

**Issue by wonboyn** [OWASP/SecurityShepherd#487]
Hi there,

In the SQL injection lesson, any value entered for user is resulting in the following stack trace:

```
secshep_tomcat | DEBUG my.user at 172.20.0.1 from ?.?.?.? @ 09 Jul 03:29:23,848 [https-openssl-nio-8443-exec-3] (SqlInjectionLesson.java:76) - SQL Injection Lesson servlet accessed by: my.user
secshep_tomcat | DEBUG my.user at 172.20.0.1 from ?.?.?.? @ 09 Jul 03:29:23,849 [https-openssl-nio-8443-exec-3] (SqlInjectionLesson.java:78) - User Submitted - fred
secshep_tomcat | DEBUG my.user at 172.20.0.1 from ?.?.?.? @ 09 Jul 03:29:23,850 [https-openssl-nio-8443-exec-3] (SqlInjectionLesson.java:80) - Servlet root = /usr/local/tomcat/webapps/ROOT/
secshep_tomcat | FATAL my.user at 172.20.0.1 from ?.?.?.? @ 09 Jul 03:29:23,855 [https-openssl-nio-8443-exec-3] (Database.java:198) - Unable to create database connection: java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'secshep_tomcat.securityshephard_default' (using password: YES)
secshep_tomcat | java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'secshep_tomcat.securityshephard_default' (using password: YES)
secshep_tomcat | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:925)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1704)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1250)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2483)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2516)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
secshep_tomcat | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
secshep_tomcat | 	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
sec
```

This is using the Docker images for v3.1

Thanks

Tim

**Comment by ismisepaul** [comment]
It looks like you are not running the mysql container? 

Did you run the docker-compose command? Did you follow these instructions https://github.com/OWASP/SecurityShepherd/wiki/Docker-Environment-Setup

Do you see the mysql container running if you issue `docker ps`

**Comment by wonboyn** [comment]
Hi,

>>Did you run the docker-compose command?

Yes.

>>Did you follow these instructions 

Yes I followed the instructions you refer to - and for the preceding lessons (security misconfig through to insecure crypto storage) it worked fine. It is only now that I have reached sql injection lesson 1 I am having an issue.

>>Do you see the mysql container running if you issue docker ps

Yes. I see both the tomcat & mysql containers running. And the stacktrace is being output to stdout/stderr in the terminal I started the containers.

**Comment by ismisepaul** [comment]
I cannot reproduce the error you're seeing. Everything is working for me.

```
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:04,873 [https-openssl-nio-8443-exec-8] (GetModule.java:139) - &&& END GetModule &&&
secshep_tomcat | DEBUG 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:05,061 [https-openssl-nio-8443-exec-6] (ShepherdLogManager.java:32) - SQL Injection Challenge One Accessed
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:05,066 [https-openssl-nio-8443-exec-6] (ShepherdLogManager.java:50) - SQL Injection Challenge One has been accessed by my.user
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,579 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:74) - SQL Injection Challenge 1 servlet accessed by: my.user
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,617 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:83) - User Submitted - fred
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,617 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:85) - Servlet root = /usr/local/tomcat/webapps/ROOT/
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,617 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:87) - Getting Connection to Database
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,618 [https-openssl-nio-8443-exec-7] (Database.java:59) - Path = SqlChallengeOne
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,618 [https-openssl-nio-8443-exec-7] (Database.java:73) - Level Properties File = SqlChallengeOne.properties
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,671 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:90) - Gathering result set
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,677 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:97) - Opening Result Set from query
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 11:57:10,681 [https-openssl-nio-8443-exec-7] (SqlInjection1.java:124) - Outputting HTML
```

However, I do notice in your log output the user for SQLChallenge1 is wrong!? Have you changed the properties files?

```
exec-3] (Database.java:198) - Unable to create database connection: java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'secshep_tomcat.securityshephard_default' (using password: YES)
secshep_tomcat | java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'secshep_tomcat.securityshephard_default' (using password: YES)
```

The user is actually: RightGuard3d you can see here https://github.com/OWASP/SecurityShepherd/blob/master/src/main/resources/challenges/SqlChallengeOne.properties

**Comment by ismisepaul** [comment]
I cannot reproduce the error you're seeing. Everything is working for me.

```
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:22,931 [https-openssl-nio-8443-exec-9] (GetModule.java:139) - &&& END GetModule &&&
secshep_tomcat | DEBUG 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:23,456 [https-openssl-nio-8443-exec-7] (ShepherdLogManager.java:32) - SQL Injection Lesson Accessed
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:23,459 [https-openssl-nio-8443-exec-7] (ShepherdLogManager.java:50) - SQL Injection Lesson has been accessed by my.user
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,897 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:76) - SQL Injection Lesson servlet accessed by: my.user
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,907 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:78) - User Submitted - fred
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,913 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:80) - Servlet root = /usr/local/tomcat/webapps/ROOT/
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,939 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:137) - Opening Result Set from query
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,939 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:145) - That's All
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,939 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:82) - output returned. [0][0] is null
secshep_tomcat | DEBUG my.user at 172.18.0.1 from ?.?.?.? @ 10 Jul 12:05:27,956 [https-openssl-nio-8443-exec-2] (SqlInjectionLesson.java:111) - Outputting HTML

```

What host OS are you using? I'm suspecting its something to do with this step in the build process;

https://github.com/OWASP/SecurityShepherd/blob/d5c716629a9ff66b9dce2360e7b11a0c34bc9674/pom.xml#L149

It has since been removed and replaced with a script which has also gone through changes to support Mac https://github.com/OWASP/SecurityShepherd/commit/152e0b3fd48b6903239d487f907b28510e1014c2#diff-5595712b5357b233972fdbde25fb1be9

I don't think the following is being done properly on your system:
```
RUN sed -i 's/@'\''localhost'\''/@'\'''"$CONTAINER_TOMCAT"'.'"$DOCKER_NETWORK_NAME"''\''/g' /docker-entrypoint-initdb.d/moduleSchemas.sql
```

which is run as part of the mysql docker file https://github.com/OWASP/SecurityShepherd/blob/master/docker/mysql/Dockerfile. 

It grants access to the tomcat server to talk to the mysql server. The maven step may not be working correctly on your OS which uses `sed`

**Comment by wonboyn** [comment]
Hi there.

I'm running the Docker containers on a Mac (v10.14.5) with Docker Community Edition.
Before trying the sed command you suggested I checked the script /docker-entrypoint-initdb.d/moduleSchemas.sql & it had the following grant for the sql injection lesson:

`GRANT USAGE ON *.* TO 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default' IDENTIFIED BY 'password';
DROP USER 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default';
CREATE USER 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default' IDENTIFIED BY 'firstBlooded';
GRANT SELECT ON `SqlInjLesson`.`tb_users` TO 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default';`

And the variables for $CONTAINER_TOMCAT & $DOCKER_NETWORK_NAME are set:
DOCKER_NETWORK_NAME=securityshepherd_default
CONTAINER_TOMCAT=secshep_tomcat

I am happy to stop & remove the containers & associated volumes and start again if there is a way to export/import my student login & progress so I don't have to start from scratch again.

Is there an easy way to export/import these details?

Cheers.

Tim

**Comment by ismisepaul** [comment]
Hi Tim,

The grant looks okay from what you shared. I hope it's not something else. The build process for 3.1 is bad in terms of it not working on other systems i.e. Mac (we didn't have capacity or equipment to test on them). We have had a lot of great community help on this and our `dev` branch should work (the Ant step has been removed)

Anyway, if you want to create a backup of your progress from your host OS issue;
```
docker exec secshep_mysql /usr/local/mysql/bin/mysqldump -u root -p'CowSaysMoo' core > shepherd_core_backup.sql
```

To restore the backup and your progress issue;
```
cat shepherd_core_backup.sql | docker exec -i secshep_mysql /usr/local/mysql/bin/mysqldump -u root -p'CowSaysMoo' core
```

If you've updated the password you'll have to adjust for that.

thanks,
Paul

**Comment by ismisepaul** [comment]
I'm going to close this issue as it's been addressed on our `dev` branch. Hopefully we'll get a release out soon enough so this fix will also be on `master`.

Feel free to open the ticket again if you don't think this is resolved on the `dev` branch.

Thanks
