### ISSUE TITLE
Testing - Move Integration Tests

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#498]
The structure of the project has changed where it has a separate unit test and integration test folder. 

Definition of done;
- all integration tests are moved to the IT folder
- all integration tests are renamed to trail with IT e.g. "lessonIT"

**Comment by smohtadi** [comment]
Hi, I could work on this. But, in regards to moving the files, do you want there to be a test folder in IT that has the same directory structure as the test directory?

**Comment by ismisepaul** [comment]
Thanks, that would be great. 

The IT tests should mirror the ```main``` folder structure - https://github.com/OWASP/SecurityShepherd/tree/dev/src/main so that if there is an integration test for a level etc. you can easily correlate it. 

I don't think there is any need to create a ```test``` folder, we'll leave that ```test``` structure for any unit tests.

**Comment by ismisepaul** [comment]
If you are going to work on this could you branch off ```dev``` and then create your own branch called ```dev#498```. Once you're happy with your changes could you create a merge request from your branch.

Thanks
