### ISSUE TITLE
Instructions for using letsencrypt or other cert?

### ISSUE THREAD

**Issue by bchurchill** [OWASP/SecurityShepherd#503]
I'd like to do better than a self-signed cert.  How can I use letsencrypt or another cert with the docker setup?

**Comment by ismisepaul** [comment]
This is a good idea, it'd be nice to easily install your own cert. 

Would you be able to do some investigation into it, all community contributions are welcomed 😃 

Cert generated here: https://github.com/OWASP/SecurityShepherd/blob/6bcce679303f43f908ecba5d89c9093159b1f564/pom.xml#L286

Used for cert install: https://github.com/OWASP/SecurityShepherd/blob/6bcce679303f43f908ecba5d89c9093159b1f564/docker/tomcat/serverxml.patch#L36


Cert installed here: https://github.com/OWASP/SecurityShepherd/blob/6bcce679303f43f908ecba5d89c9093159b1f564/Dockerfile#L39

**Comment by bchurchill** [comment]
Yeah, I can look into automating the cert install once I get things working!

**Comment by ismisepaul** [comment]
Doc created here https://github.com/OWASP/SecurityShepherd/wiki/How-to-Utilise-Let's-Encrypt-with-Docker (draft)
