### ISSUE TITLE
Data validation challenge should stop using rage faces

### ISSUE THREAD

**Issue by etnoy** [OWASP/SecurityShepherd#508]
We're using Shepherd at our uni course in infosec. Buying troll and rage faces is simply dated and should be switched out. Memes have a short expiry date 😉

Last year I made a simple change to our in house fork of Shepherd where the store sells fruit instead. I create this issue so I can track my backport progress. In the meantime we need to find images of fruit with a free license.

**Comment by ismisepaul** [comment]
closed with PR #524
