### ISSUE TITLE
Create a page for the OWASP Global Projects Page

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#533]
The projects page - https://www2.owasp.org/projects

Where to make changes - https://github.com/OWASP/www-project-security-shepherd/blob/master/index.md

**Comment by markdenihan** [comment]
https://github.com/OWASP/www-project-security-shepherd/pull/1

**Comment by ismisepaul** [comment]
It looks like the page failed to build for some reason...

https://github.com/OWASP/www-project-security-shepherd/runs/394875017
