### ISSUE TITLE
[BUG] Cross Site Scripting One exercise has a bug in XSS filtering

### ISSUE THREAD

**Issue by uzakov** [OWASP/SecurityShepherd#541]
**Describe the bug**

"Cross Site Scripting One" exercise has a bug, where XSS happens, yet no key is given to the user.

**To Reproduce**
1. Go to "Cross Site Scripting One" exercise
2. Submit following payload ` javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/"/+/onmouseover=1/+/[*/[]/+alert(1)//'>` Credits for payload: https://twitter.com/garethheyes
3. You will see that XSS happened, click OK
4. No key given to the user

**Expected behavior**
An expected behavior would be that payload bypasses the filter, XSS happens and user gets a key, to proceed to the next challenge

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox(70.0.1), IE(11.11....)

**Further Information:**
Docker - 18.09.7
Security Shepard - 3.1
Ubuntu - 18.04.3 LTS

**Screenshots**
Please see attached screenshots for more information
![XSS](https://user-images.githubusercontent.com/11824569/71966920-5a03b980-31fa-11ea-8047-967336d9785b.PNG)
![XSS1](https://user-images.githubusercontent.com/11824569/71966921-5a03b980-31fa-11ea-9dea-e63f0593b21b.PNG)
![XSS2](https://user-images.githubusercontent.com/11824569/71966923-5a03b980-31fa-11ea-9089-2de6fc252d7c.PNG)

**Comment by markdenihan** [comment]
Duplicate of #297
