### ISSUE TITLE
Is Tomcat 9 supported?

### ISSUE THREAD

**Issue by JStyle21** [OWASP/SecurityShepherd#543]
Hi,

Is tomcat9 supported?  i don't see SecurityShepherd.auth or an error for it
but v9 does have a link to /etc/tomcat9/conf in $CATALINA_HOME

**Comment by ismisepaul** [comment]
We're currently only working with 8.5.41 with no plans of supporting 9 as of yet.

https://github.com/OWASP/SecurityShepherd/blob/c555cd713d6cd28a986d32566074620f4bdf647f/.env#L3

**Comment by JStyle21** [comment]
Thanks
