### ISSUE TITLE
[BUG] Insecure Direct Object Reference Bank Challenge cant register an account

### ISSUE THREAD

**Issue by iNoSec** [OWASP/SecurityShepherd#552]
Hi,

I use the docker and that's the SecuritySheperd version 3.2
![image](https://user-images.githubusercontent.com/27919673/75615473-66dec280-5b44-11ea-99cf-484ad428c2b6.png)

im on "Insecure Direct Object Reference Bank Challenge" challenge but i cant register any account, i receive this message :

> An Error Occurred! You must be getting funky! Could not create account!

![image](https://user-images.githubusercontent.com/27919673/75615448-136c7480-5b44-11ea-97b4-268ccfbd992e.png)

So it is hard to complete the challenge xD so thanks in advance

the app doesnt pass the account_password value to the database because he cant grab it
![image](https://user-images.githubusercontent.com/27919673/75615562-727eb900-5b45-11ea-95ab-56988209a1ff.png)

**Comment by markdenihan** [comment]
@iNoSec The latest shepherd release is 3.1. Are you using a fork?

**Comment by iNoSec** [comment]
Nope i use this repo and yeah i use the 3.1 version. if you need more info like some debug log, let me know

**Comment by etnoy** [comment]
Same issue as #557

**Comment by etnoy** [comment]
Will be fixed by #531

**Comment by iNoSec** [comment]
Ok thanks, when merged i will try it and i'll be back if it is good or not :p because there isnt any duplicate name in my problem, even long random username trigger the error. Anyway will try asap

**Comment by etnoy** [comment]
For a quick fix, change the stored proc just like #557 says

**Comment by markdenihan** [comment]
#531 Is merged, @ismisepaul can you verify this is resolved with the latest dev branch?

**Comment by iNoSec2** [comment]
Now i cant even login... 
![image](https://user-images.githubusercontent.com/51358868/93181707-0fe3b800-f739-11ea-8f02-85367e614f83.png)

and in the mvn command, we have warning:
![image](https://user-images.githubusercontent.com/51358868/93181823-41f51a00-f739-11ea-8072-0f0ffb8ce6af.png)

**Comment by etnoy** [comment]
The Maven warning has been there for a long time. Could you post logs? I think that there have been changes to the stored procedures on the sql server which could cause issues.

**Comment by ismisepaul** [comment]
checked in #638
