### ISSUE TITLE
[BUG] Cannot call stored procedure `directObjectBank`.`createAccount` to complete Insecure Direct Object Reference Bank Challenge

### ISSUE THREAD

**Issue by Andrew-Stubbs** [OWASP/SecurityShepherd#557]
When attempting **Insecure Direct Object Reference Bank Challenge**, regardless of the input the request fails and the user sees **An Error Occurred! You must be getting funky! Could not create account!**

Looking through the tomcat logs,  the following error can be seen:

> secshep_tomcat | FATAL test at 172.21.0.1 from ?.?.?.? @ 29 Apr 18:16:06,290 [https-openssl-nio-8443-exec-5] (DirectObjectBankRegistration.java:94) - Insecure Direct Object Bank Challenge (Register) SQL Error - com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'account_password' cannot be null

Logging into mysql directly and calling the stored procedure results in the same:

> mysql> CALL directObjectBank.createAccount('asdf', 'asdf');
ERROR 1048 (23000): Column 'account_password' cannot be null

Looking through the code, the issue stems from the stored procedure using `SHA2(accountPassword, 191)` as the password, where *191* is not one of valid values for the second argument to SHA2 [according to the mysql documentation](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_sha2):

> ...which must have a value of 224, 256, 384, 512, or 0 (which is equivalent to 256). If either argument is NULL or the hash length is not one of the permitted values, the return value is NULL.

This can be reproduced within mysql:

> mysql> SELECT SHA2('asdf', 191);
+-------------------+
| SHA2('asdf', 191) |
+-------------------+
| NULL              |
+-------------------+

> mysql> SELECT SHA2('asdf', 256);
+------------------------------------------------------------------+
| SHA2('asdf', 256)                                                |
+------------------------------------------------------------------+
| f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b |
+------------------------------------------------------------------+
1 row in set (0.00 sec)

This bug seems to have [been introduced](https://github.com/OWASP/SecurityShepherd/commit/c57fed8b9ee4b1671480d56d2b76f05389ae839a#diff-c8415773a0bb74be38ee9ef1be9f5a9aL1114) as part of a wider change to the way passwords are stored.

**To Reproduce**
1. Log into mysql
2. Attempt to call the `directObjectBank.createAccount` procedure with any arguments
3. See `Column 'account_password' cannot be null` error

**Expected behavior**
The procedure should be callable with no errors with valid arguments

**Desktop (please complete the following information):**
 - OS: Windows 10

**Further Information:**
 - `mvn` version 3.6.3
 - `docker` version 19.03.8
 - `docker-compose` version 1.25.4

**Additional context**
Tested using the latest dev commit 35e5d82fdbaabcef1e032f7de1e07bd53d991d9f using the docker installation and deployment instructions

**Comment by etnoy** [comment]
Thanks for the bug report. I seem to have caused this issue and I'l have to fix it.

**Comment by etnoy** [comment]
This will be fixed as soon as #531 is merged

**Comment by markdenihan** [comment]
#531 Is merged, @ismisepaul can you verify this is resolved with the latest dev branch?

**Comment by ismisepaul** [comment]
verified in #638
