### ISSUE TITLE
Repo details need update

### ISSUE THREAD

**Issue by kingthorin** [OWASP/SecurityShepherd#558]
This should leverage the new website (owasp.org):
![image](https://user-images.githubusercontent.com/7570458/84726171-45221380-af5a-11ea-9284-5417550441f2.png)

https://owasp.org/www-project-security-shepherd/

**Comment by markdenihan** [comment]
Looks like I don't have access to the repo settings anymore. I'll need to find out who does

**Comment by markdenihan** [comment]
@kellysantalucia @hblankenship @mikemccamon @dawnaitken @Sibah1 @latf6711 @emilyberman @astock23 Would any of you be able to grant myself and @SeanDuggan admin access to the Security Shepherd repo?

**Comment by hblankenship** [comment]
Please let me know your github usernames.

Thanks,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by markdenihan** [comment]
@hblankenship They are "markdenihan" and "SeanDuggan"

**Comment by hblankenship** [comment]
Sorry.  I thought you were referring to the www- repository.  The permissions were not changed that I am aware (team permissions may have been though).  You are both now admin here.

**Comment by markdenihan** [comment]
Thanks @hblankenship 

Repository Website URL updated to new site. Thanks for raising this @kingthorin
