### ISSUE TITLE
[BUG] Docker environment shows Server Error when loading application

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#561]
**Describe the bug**
After commit 147d0e3 a new database parameter was introduced 
https://github.com/OWASP/SecurityShepherd/blob/147d0e3937f0569371de503b3d5791a20eddc4fa/src/main/java/dbProcs/Database.java#L157
```databaseOptions=useUnicode=true&character_set_server=utf8mb4```

However this was never added to docker so when running the user is presented with a server error;
![Screenshot from 2020-09-19 23-00-43](https://user-images.githubusercontent.com/912403/93690164-0c4f8880-facd-11ea-8b11-01c5750e68a6.png)

Suggested fix is simply to add the databaseOptions to 
https://github.com/OWASP/SecurityShepherd/blob/147d0e3937f0569371de503b3d5791a20eddc4fa/Dockerfile#L32

However, there needs to be better testing to catch this when using docker and also a better way of doing this in docker so that there's no need to do this hacky manual add of the properties files.

**Comment by etnoy** [comment]
Thanks for catching this. I don't use Docker so I never tested this, and there are no tests anywhere to catch anything in Shepherd.

**Comment by Sybrid203** [comment]
Error still persists.

**Comment by etnoy** [comment]
@ismisepaul, do you have an opportunity to do a pull request on your suggested changes?

**Comment by thomaspreece** [comment]
I've made the changes @ismisepaul suggested above in a PR. Tested and it works ok for me.

**Comment by etnoy** [comment]
Thanks. Let's get @markdenihan in here to approve the PR.

**Comment by alfasin** [comment]
+1 
Verified the same issue on both MacOS and Ubuntu

<removed previous text bc I forgot to run `docker-compose build` before running.... >

**Comment by LargeMonitorMount** [comment]
Thanks! 
+1

**Comment by ismisepaul** [comment]
Closed by https://github.com/OWASP/SecurityShepherd/pull/563

**Comment by alfasin** [comment]
Thanks @thomaspreece and @ismisepaul - much appreciated!
