### ISSUE TITLE
Deprecated File? Mobile Insecure Data Storage

### ISSUE THREAD

**Issue by BastG57** [OWASP/SecurityShepherd#567]
Hello,

Im currently at the Mobile Insecure Data Storage challenge of OWASP.
Using the android VM 3.2.3, I went to the following location :
![Annotation 2020-11-23 175919](https://user-images.githubusercontent.com/55579116/99994345-294c5480-2db9-11eb-96b7-68ea8931d089.png)
Opened the Members file with "strinigs Members" command, and get this result : 
![Annotation 2020-11-23 180001](https://user-images.githubusercontent.com/55579116/99994446-4d0f9a80-2db9-11eb-9776-786585438a85.png)

Tried to enter !AdminBattery777 as the key for the challenge but it dosnt work, neither different variation of this password.

Am I on the wrong path to the solution ?

Thanks :)

**Comment by SeanDuggan** [comment]
Hello @BastG57 the information you're reading with the strings command is correct it's just not split up with spaces or any other kind of seperator so the characters that come after the username : "Admin" are the characters of the password you're looking for.

**Comment by BastG57** [comment]
Yes I finally figured out yesterday, but I thought my post was taken out by
admin so I didnt answer, sorry

Thanks
