### ISSUE TITLE
The user of Admin can't do the “Cross Site Request Forgery Challenge One”

### ISSUE THREAD

**Issue by anquanbiji** [OWASP/SecurityShepherd#585]
Hope to remeber this thing.

Because Admin has not classid attribute in core.users, that Admin can't see the other's message and the others can't see the Admin's message. In the other words, the Admin can't be attacked by the others and the others can't be attacked by Admin.

At last, the Admin can't do the  “Cross Site Request Forgery Challenge One”

**Comment by markdenihan** [comment]
So it can still be completed, if another authenticated user submits the request for the admin. However they cannot be included in a class, so they won't end up in a table that is shown to user users. I believe that has changed in the big PR #531, so this is likely a solved in the next release. Will check that when we get some cycles to spend on Shepherd

**Comment by anquanbiji** [comment]
Thanks

My version is V3.1.
Hope it will be changed in the next version.
