### ISSUE TITLE
Fix CI/CD

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#611]
## Release to DockerHub
The Github workflow to push to DockerHub is broken.

- [x] Adjust job so that it pushes to the OWASP's DockerHub #612
- [x] Send API key to Security Shepherd maintainers
- [x] Set the following `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME` in Settings -> Secrets -> Actions
- [x] Merge #612 

## Pull requests
Pull requests cannot be complete

- [x] remove need for TravisCI to pass
- [x] set requirement for the `Build and Test` Github workflow `build, unit-test, integration-test and lint-java` to pass before merge

**Comment by markdenihan** [comment]
@ismisepaul Do you have permissions to add the secrets or would. you like me to?

**Comment by ismisepaul** [comment]
yeah I think it makes sense to add me for setting up publishing to dockerhub

**Comment by markdenihan** [comment]
@ismisepaul I've added you directly to the repo as an admin.

**Comment by ismisepaul** [comment]
Changes made
