### ISSUE TITLE
I am running security shephered on 9090 port. But when I am mapping the ip: http://xx.xx.xx.xx:9090 to my DNS. It is not working 

### ISSUE THREAD

**Issue by spmishra121** [OWASP/SecurityShepherd#616]
Hi @ismisepaul,
 
I am running my security shephered over 9090 port. If I am running it using my IP like http://xx.xx.xx.xx:9090 using VPN. It is working. But When I had mapped it with DNS. It is not working..

Running Containers:
![image](https://user-images.githubusercontent.com/6615148/160116550-1fb123f8-97a6-415d-b68b-d04423285db8.png)

**Comment by spmishra121** [comment]
Any feedback?

**Comment by ismisepaul** [comment]
Hi @spmishra121 this looks like an issue with DNS rather than Shepherd as you can load the app from the IP. 

This is probably not the best place to troubleshoot DNS and I suggest reaching out to somewhere there's expertise in that area.

**Comment by spmishra121** [comment]
Hi @ismisepaul,

Thanks for your time.

I want to understand following thing.

1. Security shepherd is used its own certificate for its internal communication. So if I am deploying this in my environment which required to use company issued certificate while mapping the IP using DNS. How we can achieve this?

**Comment by ismisepaul** [comment]
There's two options that I can think of but I'm no expect on this topic - so you'll have to test this yourself

1. Build the project and include your cert - the code responsible for the self signed cert is in the `pom.xml` and `.env`
- https://github.com/OWASP/SecurityShepherd/blob/72f87674d40e206fcad3b288f092af02a0879d99/pom.xml#L311
- https://github.com/OWASP/SecurityShepherd/blob/72f87674d40e206fcad3b288f092af02a0879d99/.env#L21
2. Replace the cert in the docker container
- HOW-TO https://tomcat.apache.org/tomcat-7.0-doc/ssl-howto.html
- Docker volume with the Tomcat config `/var/lib/docker/volumes/securityshepherd_conf/_data/`

**Comment by ismisepaul** [comment]
We've had this contribution https://github.com/OWASP/SecurityShepherd/wiki/How-to-Utilise-Let's-Encrypt-with-Docker maybe it'll help with your question?
