### ISSUE TITLE
Specify own databse container image[BUG]

### ISSUE THREAD

**Issue by xxjonesriderxx** [OWASP/SecurityShepherd#696]
Somehow your database is inside this container. Is there any possibility to specify another database connection string, so i can use another mysql databse in another container?

**Comment by ismisepaul** [comment]
Leaving this comment here for others. There are two ways you can do this

1. At build time
2. At runtime

### Build Time
Simply remove or comment out the following line from the Tomcat Dockerfile and build the image

https://github.com/OWASP/SecurityShepherd/blob/c96712026d76a9a3ecf04d914cff080fa79720bb/Dockerfile#L28

### Runtime
There is a `database.properties` file created when the docker image is built. If you remove (or move to backup) this file you can set your own database

```
➜  ~ docker exec -it secshep_tomcat /bin/bash
tomcat@f9a49394f637:~$ mv conf/database.properties conf/database.properties.bkup
```

The following setup screen will appear when there's no `database.properties` file detected when loading Tomcat. You'll need to make sure the database can be reached from the Tomcat docker container e.g. make sure they're both on the same docker network

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/912403/186379346-9967c1d3-fa1c-4a13-a3a5-be85c41c6360.png">
