### ISSUE TITLE
IDOR Example DB Access

### ISSUE THREAD

**Issue by xxjonesriderxx** [OWASP/SecurityShepherd#698]
This is a question not a bug.

Is this applicatin accessing the mariadb when using the idor example where we have to receive the admin secrets?

**Comment by ismisepaul** [comment]
It doesn't you can check the code here.

https://github.com/OWASP/SecurityShepherd/blob/c96712026d76a9a3ecf04d914cff080fa79720bb/src/main/java/servlets/module/lesson/DirectObjectLesson.java#L81
