### ISSUE TITLE
[BUG] Intercept outgoing db requests

### ISSUE THREAD

**Issue by xxjonesriderxx** [OWASP/SecurityShepherd#699]
Currently im working on an project to secure webapplications (as yours) agaiinst idor's without touching the server code. Therefor I need to access all SQL Requests between your Application and your database. 

Is there any possibility to do something like that? I know your sending JDBC requests (as every normal webapp) but i cant find a way to intercept this whit my application. Any idear?

I Already changed the db connection to point on my application.

**Comment by ismisepaul** [comment]
Hi @xxjonesriderxx I'm not sure how you can achieve this sorry its beyond the scope of this project.
