### ISSUE TITLE
[BUG] invalid LOC header

### ISSUE THREAD

**Issue by xxjonesriderxx** [OWASP/SecurityShepherd#700]
I created my own jdbc driver for java version 8 (was 11 but on your image there is only java 8).
I added my jar file to the lib folder and receiving this error.

`org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [org/idordefender/jdbcdriver/Driver.class] from Jar [file:/usr/local/tomcat/lib/idor-defender-jdbc-driver.jar] for annotations
 java.util.zip.ZipException: invalid LOC header (bad signature)`

Of couse I edited the driver in database.propertys.

**Comment by ismisepaul** [comment]
Hi @xxjonesriderxx because you're using your own jdbc driver we can't really help here as you've modified the app beyond its design. Seems like an interesting project but its not something we can help with here, sorry.
