### ISSUE TITLE
[Enhancement] Timezone, Logs volume, and letsencrypt

### ISSUE THREAD

**Issue by rudosch** [OWASP/SecurityShepherd#707]
Some enhancement suggestions, either to be implemented or added to documentation (e.g. on docker environment setup page and/or wiki):
- **Timezone** : add e.g. `CATALINA_OPTS="-Duser.timezone=Europe/Zurich"` to the `.env` file to assure correct timezone
- **Logs** : configure additional docker volume `securityshepherd_logs` in `docker-compose.yml` file to have persistent logs across tomcat builds
- **letsencrypt** : document how to adapt `Dockerfile` and `serverxml.patch` to use letsencrypt certificates (add to wiki ?). I can provide example files.

All these suggestions have been successfully tested using `dev` branch.

**Side note :** just removing tomcat container isn't sufficient if tweaking tomcat configuration, docker `conf` volume has to be removed before re-build, too. Maybe this note should be added to the docker environment setup page.

**I apologize for the wrong issue label!**

**Comment by ismisepaul** [comment]
Thanks @rudosch would you be able to provide examples for letsencrypt?

Also could you create a pull request based on your 3 points?

**Comment by rudosch** [comment]
I will do a pull request for _timezone_ and _logs,_ these are simple line additions.

But for _letsencrypt_ I think it would be better to document the needed steps in the wiki and not directly integrate those modifications in the `dev` (or `main`) branch. Otherwise, a compromise could be to add `Dockerfile-letsencrypt` and `serverxml-letsencrypt.patch` to the `dev` branch.

To use a letsencrypt certificate the following steps are needed:
- changes in `Dockerfile` : see [Dockerfile-letsencrypt.txt](https://github.com/OWASP/SecurityShepherd/files/9861230/Dockerfile-letsencrypt.txt)
- changes in `serverxml.patch` : see [serverxml.letsencrypt.patch.txt](https://github.com/OWASP/SecurityShepherd/files/9861231/serverxml.letsencrypt.patch.txt)
- add generated letsencrypt certificate files (`*.pem`) to new directory `docker/tomcat/letsencrypt`

What do you think?

**Comment by ismisepaul** [comment]
Thanks @rudosch this is awesome!

I've gone with your first suggestion and added it to the wiki https://github.com/OWASP/SecurityShepherd/wiki/How-to-Utilise-Let's-Encrypt-with-Docker

I've also located it under [Customizing](https://github.com/OWASP/SecurityShepherd/wiki#customizing)

If you could take a look, if you're happy you can go ahead with closing this issue. If there's adjustments I can go ahead and do that with you feedback. I've also reviewed and approved your PR you just need to hit the button to merge.

**Comment by rudosch** [comment]
The solution of listing the procedure in the "Customizing" section seems perfect to me. Thus I will close this issue.
But I don't think I have permission to trigger the merge ...

**Comment by ismisepaul** [comment]
Thanks for the contribution @rudosch I've merged in #dev707 just there 👍
