### ISSUE TITLE
 No Database

### ISSUE THREAD

**Issue by medrockstar** [OWASP/SecurityShepherd#743]
Hello,

it's give me in the first time :

 No Database Configuration

Security Shepherd has not detected a database configuration file. Use this form to configure your database server.

**Comment by ismisepaul** [comment]
Could you give more detail?

- What OS are you running?
- How are you deploying / running Security Shepherd?

Security Shepherd needs
- tomcat server
- mariadb
- mongodb

Please refer to these guides https://github.com/OWASP/SecurityShepherd/wiki

**Comment by medrockstar** [comment]
Could you give more detail?

What OS are you running?
MAC OS

How are you deploying / running Security Shepherd?
Docker image
docker pull ismisepaul/securityshepherd

Security Shepherd needs

tomcat server
mariadb
mongodb

I have to install these my mac os ?
