### ISSUE TITLE
[BUG] Open Floor setting is not persistent

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [OWASP/SecurityShepherd#747]
**Describe the bug**
The owaspSecurityShepherdVm v3.1 doesn't remember the Open Floor setting

**To Reproduce**
1. Power on the owaspSecurityShepherdVm v3.1 VM.
2. Use a web browser to log on to the VM's security shepherd admin account.
3. Use the side bar to navigate to Admin->Module Management->Change Module Layout.
4. Click on "Enable Open Floor Mode"
5. [At this point, you can verify that Open Floor mode has been enabled by viewing the side bar, and by logging out the admin account and logging in a regular user account to verify that, indeed, Security Shepherd is in Open Floor mode]
6. Shut down the owaspSecurityShepherdVm v3.1 VM, either by sending the ACPI Shutdown signal through Virtual Box or by logging on to the VM via the terminal and using the "shutdown" command.
7. Power on the owaspSecurityShepherdVm v3.1 VM.
8. Use a web browser to log on to the VM's security shepherd admin account (or any other account).
9. [BUG] Security Shepherd has reverted to CTF mode. Other changes, like creating new users or opening and closing modules will be persistent.

**Expected behavior**
Security Shepherd should still be in Open Floor mode when the VM is restarted.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Firefox

**Further Information:**
 - Hyper-visor: Virtual Box
 - VM distribution: owaspSecurityShepherd_v3.1_VM, October 24 2018.

**Comment by ismisepaul** [comment]
This functionality was added here https://github.com/OWASP/SecurityShepherd/blob/dev/src/main/java/utils/ModulePlan.java

However, a release has not been made with this code. You can take advantage of the code by cloning the dev branch and running the docker-compose install https://github.com/OWASP/SecurityShepherd#docker-ubuntu-linux-host
